[Metadata]
Name=简约白／Clean White
Version=1
Author=Chongyu Zhu <lembacon@gmail.com>, based on 搜狗「简约白」
Description=xmjd6 desktop palette replica (squirrel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#000000FF
HighlightColor=#000000FF
HighlightBackgroundColor=#EEEEEEFF
HighlightCandidateColor=#1589C9FF
CandidateLabelColor=#888888FF
HighlightCandidateLabelColor=#1589C9FF
CandidateCommentColor=#808080FF
HighlightCandidateCommentColor=#1589C9FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#EEEEEEFF
BorderColor=#EEEEEEFF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#EEEEEEFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#000000FF
HighlightCandidateColor=#1589C9FF

[Menu/Background]
Color=#EEEEEEFF
BorderColor=#EEEEEEFF
BorderWidth=1

[Menu/Highlight]
Color=#EEEEEEFF

[Menu/Separator]
Color=#EEEEEEFF
