[Metadata]
Name=尤加利／Eucalyptus
Version=1
Author=ID;Peace B
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#62768CFF
HighlightColor=#07102BFF
HighlightBackgroundColor=#8EA7D1FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#62768CFF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#62768CFF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FFFFFFFF
BorderColor=#81B8C9FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#8EA7D1FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#62768CFF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#FFFFFFFF
BorderColor=#81B8C9FF
BorderWidth=1

[Menu/Highlight]
Color=#8EA7D1FF

[Menu/Separator]
Color=#81B8C9FF
