[Metadata]
Name=銀色叉盒／Xbox Silver
Version=1
Author=Patricivs <ipatrickmac@me.com>
Description=xmjd6 desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#8DC21FFF
HighlightColor=#FFFFFFFF
HighlightBackgroundColor=#288C44FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#B5F05BFF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#8DC21FFF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#EEEEEFFF
BorderColor=#EEEEEFFF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#288C44FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#8DC21FFF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#EEEEEFFF
BorderColor=#EEEEEFFF
BorderWidth=1

[Menu/Highlight]
Color=#288C44FF

[Menu/Separator]
Color=#EEEEEFFF
