[Metadata]
Name=Pornhub
Version=1
Author=swwrww
Description=xmjd6 desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#FFFFFFFF
HighlightColor=#FFFFFFFF
HighlightBackgroundColor=#FF8300FF
HighlightCandidateColor=#000000FF
CandidateLabelColor=#FFFFFFFF
HighlightCandidateLabelColor=#000000FF
CandidateCommentColor=#FFFFFFFF
HighlightCandidateCommentColor=#000000FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#000000FF
BorderColor=#000000FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#FF8300FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#FFFFFFFF
HighlightCandidateColor=#000000FF

[Menu/Background]
Color=#000000FF
BorderColor=#000000FF
BorderWidth=1

[Menu/Highlight]
Color=#FF8300FF

[Menu/Separator]
Color=#000000FF
