[Metadata]
Name=NBA
Version=1
Author=Patricivs <ipatrickmac@me.com>
Description=eosphoros desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#FFFFFFFF
HighlightColor=#D71E54FF
HighlightBackgroundColor=#D71E54FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#FFFFFFFF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#FFFFFFFF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#006AB7FF
BorderColor=#006AB7FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#D71E54FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#FFFFFFFF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#006AB7FF
BorderColor=#006AB7FF
BorderWidth=1

[Menu/Highlight]
Color=#D71E54FF

[Menu/Separator]
Color=#006AB7FF
