[Metadata]
Name=Steam
Version=1
Author=Patricivs <ipatrickmac@me.com>
Description=eosphoros desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#FFFFFFFF
HighlightColor=#D1CFC9FF
HighlightBackgroundColor=#314259FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#FFFFFFFF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#A9A7A7FF
HighlightCandidateCommentColor=#A9A7A7FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#171614FF
BorderColor=#383635FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#314259FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#FFFFFFFF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#171614FF
BorderColor=#383635FF
BorderWidth=1

[Menu/Highlight]
Color=#314259FF

[Menu/Separator]
Color=#383635FF
