[Metadata]
Name=清風／Cool Breeze
Version=1
Author=skoj <skoj@qq.com>
Description=xmjd6 desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#009100FF
HighlightColor=#CE0000FF
HighlightBackgroundColor=#ACD6FFFF
HighlightCandidateColor=#3A006FFF
CandidateLabelColor=#009100FF
HighlightCandidateLabelColor=#3A006FFF
CandidateCommentColor=#009100FF
HighlightCandidateCommentColor=#3A006FFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FBFBFFFF
BorderColor=#AAAAFFFF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#ACD6FFFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#009100FF
HighlightCandidateColor=#3A006FFF

[Menu/Background]
Color=#FBFBFFFF
BorderColor=#AAAAFFFF
BorderWidth=1

[Menu/Highlight]
Color=#ACD6FFFF

[Menu/Separator]
Color=#AAAAFFFF
