[Metadata]
Name=青天／Azure
Version=1
Author=佛振 <chen.sst@gmail.com>
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#CCEAFFFF
HighlightColor=#CCEAFFFF
HighlightBackgroundColor=#000000FF
HighlightCandidateColor=#FFFE7FFF
CandidateLabelColor=#CCEAFFFF
HighlightCandidateLabelColor=#FFFE7FFF
CandidateCommentColor=#6496C6FF
HighlightCandidateCommentColor=#FFFE7FFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#014E8BEE
BorderColor=#014E8BEE
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#000000FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#CCEAFFFF
HighlightCandidateColor=#FFFE7FFF

[Menu/Background]
Color=#014E8BEE
BorderColor=#014E8BEE
BorderWidth=1

[Menu/Highlight]
Color=#000000FF

[Menu/Separator]
Color=#014E8BEE
