[Metadata]
Name=黑水鸭／Mint Dark Blue
Version=1
Author=Mintimate <"Mintimate's Blog">
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#EFEFEFFF
HighlightColor=#1AC0C6FF
HighlightBackgroundColor=#1AC0C6FF
HighlightCandidateColor=#EFEFEFFF
CandidateLabelColor=#EFEFEFFF
HighlightCandidateLabelColor=#EFEFEFFF
CandidateCommentColor=#EFEFEFFF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#424242FF
BorderColor=#424242FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#1AC0C6FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#EFEFEFFF
HighlightCandidateColor=#EFEFEFFF

[Menu/Background]
Color=#424242FF
BorderColor=#424242FF
BorderWidth=1

[Menu/Highlight]
Color=#1AC0C6FF

[Menu/Separator]
Color=#424242FF
