[Metadata]
Name=Google+
Version=1
Author=Patricivs <ipatrickmac@me.com>
Description=eosphoros desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#DD4B39FF
HighlightColor=#DD4B39FF
HighlightBackgroundColor=#DD4B39FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#C8C9CAFF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#C8C9CAFF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FFFFFFFF
BorderColor=#DD4B39FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#DD4B39FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#DD4B39FF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#FFFFFFFF
BorderColor=#DD4B39FF
BorderWidth=1

[Menu/Highlight]
Color=#DD4B39FF

[Menu/Separator]
Color=#DD4B39FF
