[Metadata]
Name=晨星·夜色／Eosphoros Dark
Version=1
Author=eosphoros-keytao
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#E6E1D8FF
HighlightColor=#F1EEE8FF
HighlightBackgroundColor=#F1EEE8FF
HighlightCandidateColor=#171716FF
CandidateLabelColor=#8B857CFF
HighlightCandidateLabelColor=#9C761DFF
CandidateCommentColor=#A7A097FF
HighlightCandidateCommentColor=#6F6550FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#171716FF
BorderColor=#383632FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#F1EEE8FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#E6E1D8FF
HighlightCandidateColor=#171716FF

[Menu/Background]
Color=#171716FF
BorderColor=#383632FF
BorderWidth=1

[Menu/Highlight]
Color=#F1EEE8FF

[Menu/Separator]
Color=#383632FF
