[Metadata]
Name=蓝黑／Easy Dark
Version=1
Author=木易
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#DBDBDBFF
HighlightColor=#D6D6D6FF
HighlightBackgroundColor=#3A4563FF
HighlightCandidateColor=#DBDBDBFF
CandidateLabelColor=#DBDBDBFF
HighlightCandidateLabelColor=#DBDBDBFF
CandidateCommentColor=#A8A8A8FF
HighlightCandidateCommentColor=#A8A8A8FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#1F2636FF
BorderColor=#1F2636FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#3A4563FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#DBDBDBFF
HighlightCandidateColor=#DBDBDBFF

[Menu/Background]
Color=#1F2636FF
BorderColor=#1F2636FF
BorderWidth=1

[Menu/Highlight]
Color=#3A4563FF

[Menu/Separator]
Color=#1F2636FF
