[Metadata]
Name=Win10Black
Version=1
Author=eosphoros desktop theme collection
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#FFFFFFFF
HighlightColor=#FFFFFFFF
HighlightBackgroundColor=#407434FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#A9A9A9FF
HighlightCandidateLabelColor=#A9A9A9FF
CandidateCommentColor=#666666FF
HighlightCandidateCommentColor=#A9A9A9FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#000000FF
BorderColor=#407434FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#407434FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#FFFFFFFF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#000000FF
BorderColor=#407434FF
BorderWidth=1

[Menu/Highlight]
Color=#407434FF

[Menu/Separator]
Color=#407434FF
