[Metadata]
Name=小鹤飞扬／flypy
Version=1
Author=Pal.lxk <Pal.lxk@gmail.com>
Description=xmjd6 desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#0080FFFF
HighlightColor=#0080FFFF
HighlightBackgroundColor=#FFFFFFFF
HighlightCandidateColor=#B00000FF
CandidateLabelColor=#0080FFFF
HighlightCandidateLabelColor=#B00000FF
CandidateCommentColor=#0080FFFF
HighlightCandidateCommentColor=#B00000FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FFFFFFFF
BorderColor=#C6C6C6FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#FFFFFFFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#0080FFFF
HighlightCandidateColor=#B00000FF

[Menu/Background]
Color=#FFFFFFFF
BorderColor=#C6C6C6FF
BorderWidth=1

[Menu/Highlight]
Color=#FFFFFFFF

[Menu/Separator]
Color=#C6C6C6FF
