[LightMode]
OverrideDefault=True
HighlightColor=#A6D8FFFF
HighlightHoverColor=#A6D8FFFF
HighlightTextColor=#000000FF
HighlightTextPressColor=#000000FF
HighlightLabelColor=#6F6F6FFF
HighlightCommentColor=#000000FF
HighlightMarkColor=#000000FF
PanelColor=#F3F3F3FF
TextColor=#000000FF
LabelColor=#6F6F6FFF
CommentColor=#000000FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#000000FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#000000FF
PreeditColorPostCaret=#000000FF
BorderColor=#DCDCDBFF
DividerColor=#DCDCDBFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#A6D8FFFF
HighlightHoverColor=#A6D8FFFF
HighlightTextColor=#000000FF
HighlightTextPressColor=#000000FF
HighlightLabelColor=#6F6F6FFF
HighlightCommentColor=#000000FF
HighlightMarkColor=#000000FF
PanelColor=#F3F3F3FF
TextColor=#000000FF
LabelColor=#6F6F6FFF
CommentColor=#000000FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#000000FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#000000FF
PreeditColorPostCaret=#000000FF
BorderColor=#DCDCDBFF
DividerColor=#DCDCDBFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
