[LightMode]
OverrideDefault=True
HighlightColor=#0078D7FF
HighlightHoverColor=#0078D7FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#000000FF
LabelColor=#838383FF
CommentColor=#000000FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#000000FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#000000FF
BorderColor=#0078D7FF
DividerColor=#0078D7FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#0078D7FF
HighlightHoverColor=#0078D7FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#000000FF
LabelColor=#838383FF
CommentColor=#000000FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#000000FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#000000FF
BorderColor=#0078D7FF
DividerColor=#0078D7FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
