[LightMode]
OverrideDefault=True
HighlightColor=#1F57FFFF
HighlightHoverColor=#1F57FFFF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#C5C5C5FF
HighlightCommentColor=#C5C5C5FF
HighlightMarkColor=#FFFFFFFF
PanelColor=#F3F3F3FF
TextColor=#4B4B4BFF
LabelColor=#4B4B4BFF
CommentColor=#4B4B4BFF
PagingButtonColor=#4B4B4BFF
DisabledPagingButtonColor=#4B4B4BFF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#000000FF
BorderColor=#E0E0E0FF
DividerColor=#E0E0E0FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#1F57FFFF
HighlightHoverColor=#1F57FFFF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#C5C5C5FF
HighlightCommentColor=#C5C5C5FF
HighlightMarkColor=#FFFFFFFF
PanelColor=#F3F3F3FF
TextColor=#4B4B4BFF
LabelColor=#4B4B4BFF
CommentColor=#4B4B4BFF
PagingButtonColor=#4B4B4BFF
DisabledPagingButtonColor=#4B4B4BFF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#000000FF
BorderColor=#E0E0E0FF
DividerColor=#E0E0E0FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
