[LightMode]
OverrideDefault=True
HighlightColor=#F16421FF
HighlightHoverColor=#F16421FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#0095D9FF
TextColor=#FFFFFFFF
LabelColor=#FFFFFFFF
CommentColor=#FFFFFFFF
PagingButtonColor=#FFFFFFFF
DisabledPagingButtonColor=#FFFFFFFF
AuxColor=#91D8F7FF
PreeditColorPreCaret=#91D8F7FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#91D8F7FF
BorderColor=#0095D9FF
DividerColor=#0095D9FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#F16421FF
HighlightHoverColor=#F16421FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#0095D9FF
TextColor=#FFFFFFFF
LabelColor=#FFFFFFFF
CommentColor=#FFFFFFFF
PagingButtonColor=#FFFFFFFF
DisabledPagingButtonColor=#FFFFFFFF
AuxColor=#91D8F7FF
PreeditColorPreCaret=#91D8F7FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#91D8F7FF
BorderColor=#0095D9FF
DividerColor=#0095D9FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
