[LightMode]
OverrideDefault=True
HighlightColor=#FFFFFFFF
HighlightHoverColor=#FFFFFFFF
HighlightTextColor=#3EB370FF
HighlightTextPressColor=#3EB370FF
HighlightLabelColor=#3EB370FF
HighlightCommentColor=#3EB370FF
HighlightMarkColor=#3EB370FF
PanelColor=#3EB370FF
TextColor=#FFFFFFFF
LabelColor=#FFFFFFFF
CommentColor=#FFFFFFFF
PagingButtonColor=#FFFFFFFF
DisabledPagingButtonColor=#FFFFFFFF
AuxColor=#3EB370FF
PreeditColorPreCaret=#3EB370FF
PreeditColorCaret=#3EB370FF
PreeditColorPostCaret=#3EB370FF
BorderColor=#3EB370FF
DividerColor=#3EB370FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#FFFFFFFF
HighlightHoverColor=#FFFFFFFF
HighlightTextColor=#3EB370FF
HighlightTextPressColor=#3EB370FF
HighlightLabelColor=#3EB370FF
HighlightCommentColor=#3EB370FF
HighlightMarkColor=#3EB370FF
PanelColor=#3EB370FF
TextColor=#FFFFFFFF
LabelColor=#FFFFFFFF
CommentColor=#FFFFFFFF
PagingButtonColor=#FFFFFFFF
DisabledPagingButtonColor=#FFFFFFFF
AuxColor=#3EB370FF
PreeditColorPreCaret=#3EB370FF
PreeditColorCaret=#3EB370FF
PreeditColorPostCaret=#3EB370FF
BorderColor=#3EB370FF
DividerColor=#3EB370FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
