[LightMode]
OverrideDefault=True
HighlightColor=#242C3BFF
HighlightHoverColor=#242C3BFF
HighlightTextColor=#E2C564FF
HighlightTextPressColor=#E2C564FF
HighlightLabelColor=#E2C564FF
HighlightCommentColor=#E2C564FF
HighlightMarkColor=#E2C564FF
PanelColor=#242C3BFF
TextColor=#E2C564FF
LabelColor=#E2C564FF
CommentColor=#8C8454FF
PagingButtonColor=#E2C564FF
DisabledPagingButtonColor=#8C8454FF
AuxColor=#E2C564FF
PreeditColorPreCaret=#E2C564FF
PreeditColorCaret=#E2C564FF
PreeditColorPostCaret=#E2C564FF
BorderColor=#396591FF
DividerColor=#396591FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#242C3BFF
HighlightHoverColor=#242C3BFF
HighlightTextColor=#E2C564FF
HighlightTextPressColor=#E2C564FF
HighlightLabelColor=#E2C564FF
HighlightCommentColor=#E2C564FF
HighlightMarkColor=#E2C564FF
PanelColor=#242C3BFF
TextColor=#E2C564FF
LabelColor=#E2C564FF
CommentColor=#8C8454FF
PagingButtonColor=#E2C564FF
DisabledPagingButtonColor=#8C8454FF
AuxColor=#E2C564FF
PreeditColorPreCaret=#E2C564FF
PreeditColorCaret=#E2C564FF
PreeditColorPostCaret=#E2C564FF
BorderColor=#396591FF
DividerColor=#396591FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
