[LightMode]
OverrideDefault=True
HighlightColor=#CCE8FFFF
HighlightHoverColor=#CCE8FFFF
HighlightTextColor=#000000FF
HighlightTextPressColor=#000000FF
HighlightLabelColor=#444444FF
HighlightCommentColor=#444444FF
HighlightMarkColor=#000000FF
PanelColor=#F2F2F2FF
TextColor=#000000FF
LabelColor=#6F6F6FFF
CommentColor=#666666FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#666666FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#000000FF
PreeditColorPostCaret=#000000FF
BorderColor=#D9D9D9FF
DividerColor=#D9D9D9FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#CCE8FFFF
HighlightHoverColor=#CCE8FFFF
HighlightTextColor=#000000FF
HighlightTextPressColor=#000000FF
HighlightLabelColor=#444444FF
HighlightCommentColor=#444444FF
HighlightMarkColor=#000000FF
PanelColor=#F2F2F2FF
TextColor=#000000FF
LabelColor=#6F6F6FFF
CommentColor=#666666FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#666666FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#000000FF
PreeditColorPostCaret=#000000FF
BorderColor=#D9D9D9FF
DividerColor=#D9D9D9FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
