[LightMode]
OverrideDefault=True
HighlightColor=#EBDBB2FF
HighlightHoverColor=#EBDBB2FF
HighlightTextColor=#000000FF
HighlightTextPressColor=#000000FF
HighlightLabelColor=#98971AFF
HighlightCommentColor=#000000FF
HighlightMarkColor=#000000FF
PanelColor=#FBF1C7FF
TextColor=#458588FF
LabelColor=#D65D0EFF
CommentColor=#7F57A2FF
PagingButtonColor=#458588FF
DisabledPagingButtonColor=#7F57A2FF
AuxColor=#CC241DFF
PreeditColorPreCaret=#CC241DFF
PreeditColorCaret=#000000FF
PreeditColorPostCaret=#CC241DFF
BorderColor=#EBDBB2FF
DividerColor=#EBDBB2FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#EBDBB2FF
HighlightHoverColor=#EBDBB2FF
HighlightTextColor=#000000FF
HighlightTextPressColor=#000000FF
HighlightLabelColor=#98971AFF
HighlightCommentColor=#000000FF
HighlightMarkColor=#000000FF
PanelColor=#FBF1C7FF
TextColor=#458588FF
LabelColor=#D65D0EFF
CommentColor=#7F57A2FF
PagingButtonColor=#458588FF
DisabledPagingButtonColor=#7F57A2FF
AuxColor=#CC241DFF
PreeditColorPreCaret=#CC241DFF
PreeditColorCaret=#000000FF
PreeditColorPostCaret=#CC241DFF
BorderColor=#EBDBB2FF
DividerColor=#EBDBB2FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
