[LightMode]
OverrideDefault=True
HighlightColor=#00000010
HighlightHoverColor=#00000010
HighlightTextColor=#DAF692FF
HighlightTextPressColor=#DAF692FF
HighlightLabelColor=#DAF692FF
HighlightCommentColor=#DAF692FF
HighlightMarkColor=#DAF692FF
PanelColor=#222222FF
TextColor=#E6E3D8FF
LabelColor=#E6E3D8FF
CommentColor=#FF6C60FF
PagingButtonColor=#E6E3D8FF
DisabledPagingButtonColor=#FF6C60FF
AuxColor=#9ACFFFFF
PreeditColorPreCaret=#9ACFFFFF
PreeditColorCaret=#DAF692FF
PreeditColorPostCaret=#9ACFFFFF
BorderColor=#222222FF
DividerColor=#222222FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#00000010
HighlightHoverColor=#00000010
HighlightTextColor=#DAF692FF
HighlightTextPressColor=#DAF692FF
HighlightLabelColor=#DAF692FF
HighlightCommentColor=#DAF692FF
HighlightMarkColor=#DAF692FF
PanelColor=#222222FF
TextColor=#E6E3D8FF
LabelColor=#E6E3D8FF
CommentColor=#FF6C60FF
PagingButtonColor=#E6E3D8FF
DisabledPagingButtonColor=#FF6C60FF
AuxColor=#9ACFFFFF
PreeditColorPreCaret=#9ACFFFFF
PreeditColorCaret=#DAF692FF
PreeditColorPostCaret=#9ACFFFFF
BorderColor=#222222FF
DividerColor=#222222FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
