[LightMode]
OverrideDefault=True
HighlightColor=#FFFFFFFF
HighlightHoverColor=#FFFFFFFF
HighlightTextColor=#DC3822FF
HighlightTextPressColor=#DC3822FF
HighlightLabelColor=#DC3822FF
HighlightCommentColor=#DC3822FF
HighlightMarkColor=#DC3822FF
PanelColor=#FFFFFFFF
TextColor=#575757FF
LabelColor=#575757FF
CommentColor=#575757FF
PagingButtonColor=#575757FF
DisabledPagingButtonColor=#575757FF
AuxColor=#DC3822FF
PreeditColorPreCaret=#DC3822FF
PreeditColorCaret=#DC3822FF
PreeditColorPostCaret=#DC3822FF
BorderColor=#333333FF
DividerColor=#333333FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#FFFFFFFF
HighlightHoverColor=#FFFFFFFF
HighlightTextColor=#DC3822FF
HighlightTextPressColor=#DC3822FF
HighlightLabelColor=#DC3822FF
HighlightCommentColor=#DC3822FF
HighlightMarkColor=#DC3822FF
PanelColor=#FFFFFFFF
TextColor=#575757FF
LabelColor=#575757FF
CommentColor=#575757FF
PagingButtonColor=#575757FF
DisabledPagingButtonColor=#575757FF
AuxColor=#DC3822FF
PreeditColorPreCaret=#DC3822FF
PreeditColorCaret=#DC3822FF
PreeditColorPostCaret=#DC3822FF
BorderColor=#333333FF
DividerColor=#333333FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
