[LightMode]
OverrideDefault=True
HighlightColor=#ACD6FFFF
HighlightHoverColor=#ACD6FFFF
HighlightTextColor=#3A006FFF
HighlightTextPressColor=#3A006FFF
HighlightLabelColor=#3A006FFF
HighlightCommentColor=#3A006FFF
HighlightMarkColor=#3A006FFF
PanelColor=#FBFBFFFF
TextColor=#009100FF
LabelColor=#009100FF
CommentColor=#009100FF
PagingButtonColor=#009100FF
DisabledPagingButtonColor=#009100FF
AuxColor=#CE0000FF
PreeditColorPreCaret=#CE0000FF
PreeditColorCaret=#3A006FFF
PreeditColorPostCaret=#CE0000FF
BorderColor=#AAAAFFFF
DividerColor=#AAAAFFFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#ACD6FFFF
HighlightHoverColor=#ACD6FFFF
HighlightTextColor=#3A006FFF
HighlightTextPressColor=#3A006FFF
HighlightLabelColor=#3A006FFF
HighlightCommentColor=#3A006FFF
HighlightMarkColor=#3A006FFF
PanelColor=#FBFBFFFF
TextColor=#009100FF
LabelColor=#009100FF
CommentColor=#009100FF
PagingButtonColor=#009100FF
DisabledPagingButtonColor=#009100FF
AuxColor=#CE0000FF
PreeditColorPreCaret=#CE0000FF
PreeditColorCaret=#3A006FFF
PreeditColorPostCaret=#CE0000FF
BorderColor=#AAAAFFFF
DividerColor=#AAAAFFFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
