[LightMode]
OverrideDefault=True
HighlightColor=#0362DAFF
HighlightHoverColor=#0362DAFF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#808080FF
HighlightMarkColor=#FFFFFFFF
PanelColor=#241F1EFF
TextColor=#E8E8E8FF
LabelColor=#7C7C7CFF
CommentColor=#0000003F
PagingButtonColor=#E8E8E8FF
DisabledPagingButtonColor=#0000003F
AuxColor=#000000D8
PreeditColorPreCaret=#000000D8
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#000000D8
BorderColor=#241F1EFF
DividerColor=#241F1EFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#0362DAFF
HighlightHoverColor=#0362DAFF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#808080FF
HighlightMarkColor=#FFFFFFFF
PanelColor=#241F1EFF
TextColor=#E8E8E8FF
LabelColor=#7C7C7CFF
CommentColor=#0000003F
PagingButtonColor=#E8E8E8FF
DisabledPagingButtonColor=#0000003F
AuxColor=#000000D8
PreeditColorPreCaret=#000000D8
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#000000D8
BorderColor=#241F1EFF
DividerColor=#241F1EFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
