[LightMode]
OverrideDefault=True
HighlightColor=#A8C450FF
HighlightHoverColor=#A8C450FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#1C7399FF
TextColor=#FFFFFFFF
LabelColor=#3588C1FF
CommentColor=#FFFFFFFF
PagingButtonColor=#FFFFFFFF
DisabledPagingButtonColor=#FFFFFFFF
AuxColor=#A8C450FF
PreeditColorPreCaret=#A8C450FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#A8C450FF
BorderColor=#1C7399FF
DividerColor=#1C7399FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#A8C450FF
HighlightHoverColor=#A8C450FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#1C7399FF
TextColor=#FFFFFFFF
LabelColor=#3588C1FF
CommentColor=#FFFFFFFF
PagingButtonColor=#FFFFFFFF
DisabledPagingButtonColor=#FFFFFFFF
AuxColor=#A8C450FF
PreeditColorPreCaret=#A8C450FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#A8C450FF
BorderColor=#1C7399FF
DividerColor=#1C7399FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
