[LightMode]
OverrideDefault=True
HighlightColor=#F1EEE8FF
HighlightHoverColor=#F1EEE8FF
HighlightTextColor=#171716FF
HighlightTextPressColor=#171716FF
HighlightLabelColor=#9C761DFF
HighlightCommentColor=#6F6550FF
HighlightMarkColor=#171716FF
PanelColor=#171716FF
TextColor=#E6E1D8FF
LabelColor=#8B857CFF
CommentColor=#A7A097FF
PagingButtonColor=#E6E1D8FF
DisabledPagingButtonColor=#A7A097FF
AuxColor=#F1EEE8FF
PreeditColorPreCaret=#F1EEE8FF
PreeditColorCaret=#171716FF
PreeditColorPostCaret=#F1EEE8FF
BorderColor=#383632FF
DividerColor=#383632FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#F1EEE8FF
HighlightHoverColor=#F1EEE8FF
HighlightTextColor=#171716FF
HighlightTextPressColor=#171716FF
HighlightLabelColor=#9C761DFF
HighlightCommentColor=#6F6550FF
HighlightMarkColor=#171716FF
PanelColor=#171716FF
TextColor=#E6E1D8FF
LabelColor=#8B857CFF
CommentColor=#A7A097FF
PagingButtonColor=#E6E1D8FF
DisabledPagingButtonColor=#A7A097FF
AuxColor=#F1EEE8FF
PreeditColorPreCaret=#F1EEE8FF
PreeditColorCaret=#171716FF
PreeditColorPostCaret=#F1EEE8FF
BorderColor=#383632FF
DividerColor=#383632FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
