[LightMode]
OverrideDefault=True
HighlightColor=#444444FF
HighlightHoverColor=#444444FF
HighlightTextColor=#EDEDEDFF
HighlightTextPressColor=#EDEDEDFF
HighlightLabelColor=#EDEDEDFF
HighlightCommentColor=#EDEDEDFF
HighlightMarkColor=#EDEDEDFF
PanelColor=#EDEDEDFF
TextColor=#444444FF
LabelColor=#444444FF
CommentColor=#444444FF
PagingButtonColor=#444444FF
DisabledPagingButtonColor=#444444FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#EDEDEDFF
PreeditColorPostCaret=#000000FF
BorderColor=#44444440
DividerColor=#44444440

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#444444FF
HighlightHoverColor=#444444FF
HighlightTextColor=#EDEDEDFF
HighlightTextPressColor=#EDEDEDFF
HighlightLabelColor=#EDEDEDFF
HighlightCommentColor=#EDEDEDFF
HighlightMarkColor=#EDEDEDFF
PanelColor=#EDEDEDFF
TextColor=#444444FF
LabelColor=#444444FF
CommentColor=#444444FF
PagingButtonColor=#444444FF
DisabledPagingButtonColor=#444444FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#EDEDEDFF
PreeditColorPostCaret=#000000FF
BorderColor=#44444440
DividerColor=#44444440

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
