[LightMode]
OverrideDefault=True
HighlightColor=#C82428FF
HighlightHoverColor=#C82428FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#C82428FF
TextColor=#F2C3C5FF
LabelColor=#F2C3C5FF
CommentColor=#FFFFFFFF
PagingButtonColor=#F2C3C5FF
DisabledPagingButtonColor=#FFFFFFFF
AuxColor=#FFFFFFFF
PreeditColorPreCaret=#FFFFFFFF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#FFFFFFFF
BorderColor=#C82428FF
DividerColor=#C82428FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#C82428FF
HighlightHoverColor=#C82428FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#C82428FF
TextColor=#F2C3C5FF
LabelColor=#F2C3C5FF
CommentColor=#FFFFFFFF
PagingButtonColor=#F2C3C5FF
DisabledPagingButtonColor=#FFFFFFFF
AuxColor=#FFFFFFFF
PreeditColorPreCaret=#FFFFFFFF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#FFFFFFFF
BorderColor=#C82428FF
DividerColor=#C82428FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
