[LightMode]
OverrideDefault=True
HighlightColor=#434C5DFF
HighlightHoverColor=#434C5DFF
HighlightTextColor=#77E0C0FF
HighlightTextPressColor=#77E0C0FF
HighlightLabelColor=#77E0C0FF
HighlightCommentColor=#77E0C0FF
HighlightMarkColor=#77E0C0FF
PanelColor=#333A47FF
TextColor=#87D8F5FF
LabelColor=#87D8F5FF
CommentColor=#87B6E6FF
PagingButtonColor=#87D8F5FF
DisabledPagingButtonColor=#87B6E6FF
AuxColor=#F5C86EFF
PreeditColorPreCaret=#F5C86EFF
PreeditColorCaret=#77E0C0FF
PreeditColorPostCaret=#F5C86EFF
BorderColor=#333A47FF
DividerColor=#333A47FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#434C5DFF
HighlightHoverColor=#434C5DFF
HighlightTextColor=#77E0C0FF
HighlightTextPressColor=#77E0C0FF
HighlightLabelColor=#77E0C0FF
HighlightCommentColor=#77E0C0FF
HighlightMarkColor=#77E0C0FF
PanelColor=#333A47FF
TextColor=#87D8F5FF
LabelColor=#87D8F5FF
CommentColor=#87B6E6FF
PagingButtonColor=#87D8F5FF
DisabledPagingButtonColor=#87B6E6FF
AuxColor=#F5C86EFF
PreeditColorPreCaret=#F5C86EFF
PreeditColorCaret=#77E0C0FF
PreeditColorPostCaret=#F5C86EFF
BorderColor=#333A47FF
DividerColor=#333A47FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
