[LightMode]
OverrideDefault=True
HighlightColor=#000000FF
HighlightHoverColor=#000000FF
HighlightTextColor=#FFFE7FFF
HighlightTextPressColor=#FFFE7FFF
HighlightLabelColor=#FFFE7FFF
HighlightCommentColor=#FFFE7FFF
HighlightMarkColor=#FFFE7FFF
PanelColor=#014E8BEE
TextColor=#CCEAFFFF
LabelColor=#CCEAFFFF
CommentColor=#6496C6FF
PagingButtonColor=#CCEAFFFF
DisabledPagingButtonColor=#6496C6FF
AuxColor=#CCEAFFFF
PreeditColorPreCaret=#CCEAFFFF
PreeditColorCaret=#FFFE7FFF
PreeditColorPostCaret=#CCEAFFFF
BorderColor=#014E8BEE
DividerColor=#014E8BEE

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#000000FF
HighlightHoverColor=#000000FF
HighlightTextColor=#FFFE7FFF
HighlightTextPressColor=#FFFE7FFF
HighlightLabelColor=#FFFE7FFF
HighlightCommentColor=#FFFE7FFF
HighlightMarkColor=#FFFE7FFF
PanelColor=#014E8BEE
TextColor=#CCEAFFFF
LabelColor=#CCEAFFFF
CommentColor=#6496C6FF
PagingButtonColor=#CCEAFFFF
DisabledPagingButtonColor=#6496C6FF
AuxColor=#CCEAFFFF
PreeditColorPreCaret=#CCEAFFFF
PreeditColorCaret=#FFFE7FFF
PreeditColorPostCaret=#CCEAFFFF
BorderColor=#014E8BEE
DividerColor=#014E8BEE

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
