[LightMode]
OverrideDefault=True
HighlightColor=#CCCCCCFF
HighlightHoverColor=#CCCCCCFF
HighlightTextColor=#000000FF
HighlightTextPressColor=#000000FF
HighlightLabelColor=#444444FF
HighlightCommentColor=#555555FF
HighlightMarkColor=#000000FF
PanelColor=#F4F4F4FF
TextColor=#000000FF
LabelColor=#888888FF
CommentColor=#666666FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#666666FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#000000FF
PreeditColorPostCaret=#000000FF
BorderColor=#CCCCCCFF
DividerColor=#CCCCCCFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#CCCCCCFF
HighlightHoverColor=#CCCCCCFF
HighlightTextColor=#000000FF
HighlightTextPressColor=#000000FF
HighlightLabelColor=#444444FF
HighlightCommentColor=#555555FF
HighlightMarkColor=#000000FF
PanelColor=#F4F4F4FF
TextColor=#000000FF
LabelColor=#888888FF
CommentColor=#666666FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#666666FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#000000FF
PreeditColorPostCaret=#000000FF
BorderColor=#CCCCCCFF
DividerColor=#CCCCCCFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
