[LightMode]
OverrideDefault=True
HighlightColor=#00BCD4FF
HighlightHoverColor=#00BCD4FF
HighlightTextColor=#FAFAFAFF
HighlightTextPressColor=#FAFAFAFF
HighlightLabelColor=#FAFAFAFF
HighlightCommentColor=#444444FF
HighlightMarkColor=#FAFAFAFF
PanelColor=#444444FF
TextColor=#EEEEEEFF
LabelColor=#EEEEEEFF
CommentColor=#808080FF
PagingButtonColor=#EEEEEEFF
DisabledPagingButtonColor=#808080FF
AuxColor=#EEEEEEFF
PreeditColorPreCaret=#EEEEEEFF
PreeditColorCaret=#FAFAFAFF
PreeditColorPostCaret=#EEEEEEFF
BorderColor=#444444FF
DividerColor=#444444FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#00BCD4FF
HighlightHoverColor=#00BCD4FF
HighlightTextColor=#FAFAFAFF
HighlightTextPressColor=#FAFAFAFF
HighlightLabelColor=#FAFAFAFF
HighlightCommentColor=#444444FF
HighlightMarkColor=#FAFAFAFF
PanelColor=#444444FF
TextColor=#EEEEEEFF
LabelColor=#EEEEEEFF
CommentColor=#808080FF
PagingButtonColor=#EEEEEEFF
DisabledPagingButtonColor=#808080FF
AuxColor=#EEEEEEFF
PreeditColorPreCaret=#EEEEEEFF
PreeditColorCaret=#FAFAFAFF
PreeditColorPostCaret=#EEEEEEFF
BorderColor=#444444FF
DividerColor=#444444FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
