[LightMode]
OverrideDefault=True
HighlightColor=#FFFFFFFF
HighlightHoverColor=#FFFFFFFF
HighlightTextColor=#B00000FF
HighlightTextPressColor=#B00000FF
HighlightLabelColor=#B00000FF
HighlightCommentColor=#B00000FF
HighlightMarkColor=#B00000FF
PanelColor=#FFFFFFFF
TextColor=#0080FFFF
LabelColor=#0080FFFF
CommentColor=#0080FFFF
PagingButtonColor=#0080FFFF
DisabledPagingButtonColor=#0080FFFF
AuxColor=#0080FFFF
PreeditColorPreCaret=#0080FFFF
PreeditColorCaret=#B00000FF
PreeditColorPostCaret=#0080FFFF
BorderColor=#C6C6C6FF
DividerColor=#C6C6C6FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#FFFFFFFF
HighlightHoverColor=#FFFFFFFF
HighlightTextColor=#B00000FF
HighlightTextPressColor=#B00000FF
HighlightLabelColor=#B00000FF
HighlightCommentColor=#B00000FF
HighlightMarkColor=#B00000FF
PanelColor=#FFFFFFFF
TextColor=#0080FFFF
LabelColor=#0080FFFF
CommentColor=#0080FFFF
PagingButtonColor=#0080FFFF
DisabledPagingButtonColor=#0080FFFF
AuxColor=#0080FFFF
PreeditColorPreCaret=#0080FFFF
PreeditColorCaret=#B00000FF
PreeditColorPostCaret=#0080FFFF
BorderColor=#C6C6C6FF
DividerColor=#C6C6C6FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
