[LightMode]
OverrideDefault=True
HighlightColor=#1E1D1AFF
HighlightHoverColor=#1E1D1AFF
HighlightTextColor=#FFF9EDFF
HighlightTextPressColor=#FFF9EDFF
HighlightLabelColor=#F0C96AFF
HighlightCommentColor=#D9C89FFF
HighlightMarkColor=#FFF9EDFF
PanelColor=#F7F5F1FF
TextColor=#32302CFF
LabelColor=#9A9286FF
CommentColor=#7B746AFF
PagingButtonColor=#32302CFF
DisabledPagingButtonColor=#7B746AFF
AuxColor=#171717FF
PreeditColorPreCaret=#171717FF
PreeditColorCaret=#FFF9EDFF
PreeditColorPostCaret=#171717FF
BorderColor=#D8D1C5FF
DividerColor=#D8D1C5FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#1E1D1AFF
HighlightHoverColor=#1E1D1AFF
HighlightTextColor=#FFF9EDFF
HighlightTextPressColor=#FFF9EDFF
HighlightLabelColor=#F0C96AFF
HighlightCommentColor=#D9C89FFF
HighlightMarkColor=#FFF9EDFF
PanelColor=#F7F5F1FF
TextColor=#32302CFF
LabelColor=#9A9286FF
CommentColor=#7B746AFF
PagingButtonColor=#32302CFF
DisabledPagingButtonColor=#7B746AFF
AuxColor=#171717FF
PreeditColorPreCaret=#171717FF
PreeditColorCaret=#FFF9EDFF
PreeditColorPostCaret=#171717FF
BorderColor=#D8D1C5FF
DividerColor=#D8D1C5FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
