[LightMode]
OverrideDefault=True
HighlightColor=#F0F0F0FF
HighlightHoverColor=#F0F0F0FF
HighlightTextColor=#000000FF
HighlightTextPressColor=#000000FF
HighlightLabelColor=#424242FF
HighlightCommentColor=#424242FF
HighlightMarkColor=#000000FF
PanelColor=#F9F9F9FF
TextColor=#000000FF
LabelColor=#7C7C7CFF
CommentColor=#616161FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#616161FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#000000FF
PreeditColorPostCaret=#000000FF
BorderColor=#E5E5E5FF
DividerColor=#E5E5E5FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#F0F0F0FF
HighlightHoverColor=#F0F0F0FF
HighlightTextColor=#000000FF
HighlightTextPressColor=#000000FF
HighlightLabelColor=#424242FF
HighlightCommentColor=#424242FF
HighlightMarkColor=#000000FF
PanelColor=#F9F9F9FF
TextColor=#000000FF
LabelColor=#7C7C7CFF
CommentColor=#616161FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#616161FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#000000FF
PreeditColorPostCaret=#000000FF
BorderColor=#E5E5E5FF
DividerColor=#E5E5E5FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
