[LightMode]
OverrideDefault=True
HighlightColor=#6DBCDBFF
HighlightHoverColor=#6DBCDBFF
HighlightTextColor=#F6F6F6FF
HighlightTextPressColor=#F6F6F6FF
HighlightLabelColor=#F6F6F6FF
HighlightCommentColor=#F6F6F6FF
HighlightMarkColor=#F6F6F6FF
PanelColor=#1778BFFF
TextColor=#F6F6F6FF
LabelColor=#1778BFFF
CommentColor=#F6F6F6FF
PagingButtonColor=#F6F6F6FF
DisabledPagingButtonColor=#F6F6F6FF
AuxColor=#6DBCDBFF
PreeditColorPreCaret=#6DBCDBFF
PreeditColorCaret=#F6F6F6FF
PreeditColorPostCaret=#6DBCDBFF
BorderColor=#E0EDF5FF
DividerColor=#E0EDF5FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#6DBCDBFF
HighlightHoverColor=#6DBCDBFF
HighlightTextColor=#F6F6F6FF
HighlightTextPressColor=#F6F6F6FF
HighlightLabelColor=#F6F6F6FF
HighlightCommentColor=#F6F6F6FF
HighlightMarkColor=#F6F6F6FF
PanelColor=#1778BFFF
TextColor=#F6F6F6FF
LabelColor=#1778BFFF
CommentColor=#F6F6F6FF
PagingButtonColor=#F6F6F6FF
DisabledPagingButtonColor=#F6F6F6FF
AuxColor=#6DBCDBFF
PreeditColorPreCaret=#6DBCDBFF
PreeditColorCaret=#F6F6F6FF
PreeditColorPostCaret=#6DBCDBFF
BorderColor=#E0EDF5FF
DividerColor=#E0EDF5FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
