[LightMode]
OverrideDefault=True
HighlightColor=#202020FF
HighlightHoverColor=#202020FF
HighlightTextColor=#F9F9F9FF
HighlightTextPressColor=#F9F9F9FF
HighlightLabelColor=#F9F9F9FF
HighlightCommentColor=#F9F9F9FF
HighlightMarkColor=#F9F9F9FF
PanelColor=#303030FF
TextColor=#C9C9C9FF
LabelColor=#C9C9C9FF
CommentColor=#C9C9C9FF
PagingButtonColor=#C9C9C9FF
DisabledPagingButtonColor=#C9C9C9FF
AuxColor=#F9F9F9FF
PreeditColorPreCaret=#F9F9F9FF
PreeditColorCaret=#F9F9F9FF
PreeditColorPostCaret=#F9F9F9FF
BorderColor=#2020200C
DividerColor=#2020200C

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#202020FF
HighlightHoverColor=#202020FF
HighlightTextColor=#F9F9F9FF
HighlightTextPressColor=#F9F9F9FF
HighlightLabelColor=#F9F9F9FF
HighlightCommentColor=#F9F9F9FF
HighlightMarkColor=#F9F9F9FF
PanelColor=#303030FF
TextColor=#C9C9C9FF
LabelColor=#C9C9C9FF
CommentColor=#C9C9C9FF
PagingButtonColor=#C9C9C9FF
DisabledPagingButtonColor=#C9C9C9FF
AuxColor=#F9F9F9FF
PreeditColorPreCaret=#F9F9F9FF
PreeditColorCaret=#F9F9F9FF
PreeditColorPostCaret=#F9F9F9FF
BorderColor=#2020200C
DividerColor=#2020200C

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
