[LightMode]
OverrideDefault=True
HighlightColor=#EDE8D7FF
HighlightHoverColor=#EDE8D7FF
HighlightTextColor=#CB4239FF
HighlightTextPressColor=#CB4239FF
HighlightLabelColor=#CB4239FF
HighlightCommentColor=#C24481FF
HighlightMarkColor=#CB4239FF
PanelColor=#FBF6E5F0
TextColor=#005E59FF
LabelColor=#0764A3FF
CommentColor=#475900FF
PagingButtonColor=#005E59FF
DisabledPagingButtonColor=#475900FF
AuxColor=#AE8B2CFF
PreeditColorPreCaret=#AE8B2CFF
PreeditColorCaret=#CB4239FF
PreeditColorPostCaret=#AE8B2CFF
BorderColor=#FFFFEDFF
DividerColor=#FFFFEDFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#EDE8D7FF
HighlightHoverColor=#EDE8D7FF
HighlightTextColor=#CB4239FF
HighlightTextPressColor=#CB4239FF
HighlightLabelColor=#CB4239FF
HighlightCommentColor=#C24481FF
HighlightMarkColor=#CB4239FF
PanelColor=#FBF6E5F0
TextColor=#005E59FF
LabelColor=#0764A3FF
CommentColor=#475900FF
PagingButtonColor=#005E59FF
DisabledPagingButtonColor=#475900FF
AuxColor=#AE8B2CFF
PreeditColorPreCaret=#AE8B2CFF
PreeditColorCaret=#CB4239FF
PreeditColorPostCaret=#AE8B2CFF
BorderColor=#FFFFEDFF
DividerColor=#FFFFEDFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
