[LightMode]
OverrideDefault=True
HighlightColor=#556B73FF
HighlightHoverColor=#556B73FF
HighlightTextColor=#EEE8D5FF
HighlightTextPressColor=#EEE8D5FF
HighlightLabelColor=#EEE8D5FF
HighlightCommentColor=#EEE8D5FF
HighlightMarkColor=#EEE8D5FF
PanelColor=#FDF6E3FF
TextColor=#556B73FF
LabelColor=#839191FF
CommentColor=#B97793FF
PagingButtonColor=#556B73FF
DisabledPagingButtonColor=#B97793FF
AuxColor=#EEE8D5FF
PreeditColorPreCaret=#EEE8D5FF
PreeditColorCaret=#EEE8D5FF
PreeditColorPostCaret=#EEE8D5FF
BorderColor=#CCC8C5FF
DividerColor=#CCC8C5FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#556B73FF
HighlightHoverColor=#556B73FF
HighlightTextColor=#EEE8D5FF
HighlightTextPressColor=#EEE8D5FF
HighlightLabelColor=#EEE8D5FF
HighlightCommentColor=#EEE8D5FF
HighlightMarkColor=#EEE8D5FF
PanelColor=#FDF6E3FF
TextColor=#556B73FF
LabelColor=#839191FF
CommentColor=#B97793FF
PagingButtonColor=#556B73FF
DisabledPagingButtonColor=#B97793FF
AuxColor=#EEE8D5FF
PreeditColorPreCaret=#EEE8D5FF
PreeditColorCaret=#EEE8D5FF
PreeditColorPostCaret=#EEE8D5FF
BorderColor=#CCC8C5FF
DividerColor=#CCC8C5FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
