[LightMode]
OverrideDefault=True
HighlightColor=#FFFFFFFF
HighlightHoverColor=#FFFFFFFF
HighlightTextColor=#FFD900FF
HighlightTextPressColor=#FFD900FF
HighlightLabelColor=#FFD900FF
HighlightCommentColor=#FFD900FF
HighlightMarkColor=#FFD900FF
PanelColor=#00A381FF
TextColor=#FFFFFFFF
LabelColor=#FFFFFFFF
CommentColor=#FFFFFFFF
PagingButtonColor=#FFFFFFFF
DisabledPagingButtonColor=#FFFFFFFF
AuxColor=#FFFFFFFF
PreeditColorPreCaret=#FFFFFFFF
PreeditColorCaret=#FFD900FF
PreeditColorPostCaret=#FFFFFFFF
BorderColor=#00A381FF
DividerColor=#00A381FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#FFFFFFFF
HighlightHoverColor=#FFFFFFFF
HighlightTextColor=#FFD900FF
HighlightTextPressColor=#FFD900FF
HighlightLabelColor=#FFD900FF
HighlightCommentColor=#FFD900FF
HighlightMarkColor=#FFD900FF
PanelColor=#00A381FF
TextColor=#FFFFFFFF
LabelColor=#FFFFFFFF
CommentColor=#FFFFFFFF
PagingButtonColor=#FFFFFFFF
DisabledPagingButtonColor=#FFFFFFFF
AuxColor=#FFFFFFFF
PreeditColorPreCaret=#FFFFFFFF
PreeditColorCaret=#FFD900FF
PreeditColorPostCaret=#FFFFFFFF
BorderColor=#00A381FF
DividerColor=#00A381FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
