[LightMode]
OverrideDefault=True
HighlightColor=#3A4563FF
HighlightHoverColor=#3A4563FF
HighlightTextColor=#DBDBDBFF
HighlightTextPressColor=#DBDBDBFF
HighlightLabelColor=#DBDBDBFF
HighlightCommentColor=#A8A8A8FF
HighlightMarkColor=#DBDBDBFF
PanelColor=#1F2636FF
TextColor=#DBDBDBFF
LabelColor=#DBDBDBFF
CommentColor=#A8A8A8FF
PagingButtonColor=#DBDBDBFF
DisabledPagingButtonColor=#A8A8A8FF
AuxColor=#D6D6D6FF
PreeditColorPreCaret=#D6D6D6FF
PreeditColorCaret=#DBDBDBFF
PreeditColorPostCaret=#D6D6D6FF
BorderColor=#1F2636FF
DividerColor=#1F2636FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#3A4563FF
HighlightHoverColor=#3A4563FF
HighlightTextColor=#DBDBDBFF
HighlightTextPressColor=#DBDBDBFF
HighlightLabelColor=#DBDBDBFF
HighlightCommentColor=#A8A8A8FF
HighlightMarkColor=#DBDBDBFF
PanelColor=#1F2636FF
TextColor=#DBDBDBFF
LabelColor=#DBDBDBFF
CommentColor=#A8A8A8FF
PagingButtonColor=#DBDBDBFF
DisabledPagingButtonColor=#A8A8A8FF
AuxColor=#D6D6D6FF
PreeditColorPreCaret=#D6D6D6FF
PreeditColorCaret=#DBDBDBFF
PreeditColorPostCaret=#D6D6D6FF
BorderColor=#1F2636FF
DividerColor=#1F2636FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
