[LightMode]
OverrideDefault=True
HighlightColor=#009FE8FF
HighlightHoverColor=#009FE8FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#009FE8FF
LabelColor=#009FE8FF
CommentColor=#009FE8FF
PagingButtonColor=#009FE8FF
DisabledPagingButtonColor=#009FE8FF
AuxColor=#FFFFFFFF
PreeditColorPreCaret=#FFFFFFFF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#FFFFFFFF
BorderColor=#009FE8FF
DividerColor=#009FE8FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#009FE8FF
HighlightHoverColor=#009FE8FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#009FE8FF
LabelColor=#009FE8FF
CommentColor=#009FE8FF
PagingButtonColor=#009FE8FF
DisabledPagingButtonColor=#009FE8FF
AuxColor=#FFFFFFFF
PreeditColorPreCaret=#FFFFFFFF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#FFFFFFFF
BorderColor=#009FE8FF
DividerColor=#009FE8FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
