[LightMode]
OverrideDefault=True
HighlightColor=#000000FF
HighlightHoverColor=#000000FF
HighlightTextColor=#AFFF70FF
HighlightTextPressColor=#AFFF70FF
HighlightLabelColor=#AFFF70FF
HighlightCommentColor=#F01010FF
HighlightMarkColor=#AFFF70FF
PanelColor=#000000EE
TextColor=#55BB30FF
LabelColor=#55BB30FF
CommentColor=#D01010FF
PagingButtonColor=#55BB30FF
DisabledPagingButtonColor=#D01010FF
AuxColor=#96CBFEFF
PreeditColorPreCaret=#96CBFEFF
PreeditColorCaret=#AFFF70FF
PreeditColorPostCaret=#96CBFEFF
BorderColor=#A01010FF
DividerColor=#A01010FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#000000FF
HighlightHoverColor=#000000FF
HighlightTextColor=#AFFF70FF
HighlightTextPressColor=#AFFF70FF
HighlightLabelColor=#AFFF70FF
HighlightCommentColor=#F01010FF
HighlightMarkColor=#AFFF70FF
PanelColor=#000000EE
TextColor=#55BB30FF
LabelColor=#55BB30FF
CommentColor=#D01010FF
PagingButtonColor=#55BB30FF
DisabledPagingButtonColor=#D01010FF
AuxColor=#96CBFEFF
PreeditColorPreCaret=#96CBFEFF
PreeditColorCaret=#AFFF70FF
PreeditColorPostCaret=#96CBFEFF
BorderColor=#A01010FF
DividerColor=#A01010FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
