[LightMode]
OverrideDefault=True
HighlightColor=#407434FF
HighlightHoverColor=#407434FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#A9A9A9FF
HighlightCommentColor=#A9A9A9FF
HighlightMarkColor=#FFFFFFFF
PanelColor=#000000FF
TextColor=#FFFFFFFF
LabelColor=#A9A9A9FF
CommentColor=#666666FF
PagingButtonColor=#FFFFFFFF
DisabledPagingButtonColor=#666666FF
AuxColor=#FFFFFFFF
PreeditColorPreCaret=#FFFFFFFF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#FFFFFFFF
BorderColor=#407434FF
DividerColor=#407434FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#407434FF
HighlightHoverColor=#407434FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#A9A9A9FF
HighlightCommentColor=#A9A9A9FF
HighlightMarkColor=#FFFFFFFF
PanelColor=#000000FF
TextColor=#FFFFFFFF
LabelColor=#A9A9A9FF
CommentColor=#666666FF
PagingButtonColor=#FFFFFFFF
DisabledPagingButtonColor=#666666FF
AuxColor=#FFFFFFFF
PreeditColorPreCaret=#FFFFFFFF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#FFFFFFFF
BorderColor=#407434FF
DividerColor=#407434FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
