[LightMode]
OverrideDefault=True
HighlightColor=#4DAAF8FF
HighlightHoverColor=#4DAAF8FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#999999FF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#3C3C3CFF
LabelColor=#999999FF
CommentColor=#999999FF
PagingButtonColor=#3C3C3CFF
DisabledPagingButtonColor=#999999FF
AuxColor=#999999FF
PreeditColorPreCaret=#999999FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#999999FF
BorderColor=#FFFFFFFF
DividerColor=#FFFFFFFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#4DAAF8FF
HighlightHoverColor=#4DAAF8FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#999999FF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#3C3C3CFF
LabelColor=#999999FF
CommentColor=#999999FF
PagingButtonColor=#3C3C3CFF
DisabledPagingButtonColor=#999999FF
AuxColor=#999999FF
PreeditColorPreCaret=#999999FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#999999FF
BorderColor=#FFFFFFFF
DividerColor=#FFFFFFFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
