[LightMode]
OverrideDefault=True
HighlightColor=#C30D23FF
HighlightHoverColor=#C30D23FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#DEDEDEFF
TextColor=#000000FF
LabelColor=#000000FF
CommentColor=#000000FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#000000FF
AuxColor=#C30D23FF
PreeditColorPreCaret=#C30D23FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#C30D23FF
BorderColor=#DEDEDEFF
DividerColor=#DEDEDEFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#C30D23FF
HighlightHoverColor=#C30D23FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#DEDEDEFF
TextColor=#000000FF
LabelColor=#000000FF
CommentColor=#000000FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#000000FF
AuxColor=#C30D23FF
PreeditColorPreCaret=#C30D23FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#C30D23FF
BorderColor=#DEDEDEFF
DividerColor=#DEDEDEFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
