[LightMode]
OverrideDefault=True
HighlightColor=#8EA7D1FF
HighlightHoverColor=#8EA7D1FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#62768CFF
LabelColor=#62768CFF
CommentColor=#62768CFF
PagingButtonColor=#62768CFF
DisabledPagingButtonColor=#62768CFF
AuxColor=#07102BFF
PreeditColorPreCaret=#07102BFF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#07102BFF
BorderColor=#81B8C9FF
DividerColor=#81B8C9FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#8EA7D1FF
HighlightHoverColor=#8EA7D1FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#62768CFF
LabelColor=#62768CFF
CommentColor=#62768CFF
PagingButtonColor=#62768CFF
DisabledPagingButtonColor=#62768CFF
AuxColor=#07102BFF
PreeditColorPreCaret=#07102BFF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#07102BFF
BorderColor=#81B8C9FF
DividerColor=#81B8C9FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
