[LightMode]
OverrideDefault=True
HighlightColor=#FCE4ECFF
HighlightHoverColor=#FCE4ECFF
HighlightTextColor=#EC407AFF
HighlightTextPressColor=#EC407AFF
HighlightLabelColor=#F48FB1FF
HighlightCommentColor=#EC407AFF
HighlightMarkColor=#EC407AFF
PanelColor=#FFFFFFFF
TextColor=#121212FF
LabelColor=#858788FF
CommentColor=#8E8E8EFF
PagingButtonColor=#121212FF
DisabledPagingButtonColor=#8E8E8EFF
AuxColor=#EB0081FF
PreeditColorPreCaret=#EB0081FF
PreeditColorCaret=#EC407AFF
PreeditColorPostCaret=#EB0081FF
BorderColor=#FFFFFFFF
DividerColor=#FFFFFFFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#FCE4ECFF
HighlightHoverColor=#FCE4ECFF
HighlightTextColor=#EC407AFF
HighlightTextPressColor=#EC407AFF
HighlightLabelColor=#F48FB1FF
HighlightCommentColor=#EC407AFF
HighlightMarkColor=#EC407AFF
PanelColor=#FFFFFFFF
TextColor=#121212FF
LabelColor=#858788FF
CommentColor=#8E8E8EFF
PagingButtonColor=#121212FF
DisabledPagingButtonColor=#8E8E8EFF
AuxColor=#EB0081FF
PreeditColorPreCaret=#EB0081FF
PreeditColorCaret=#EC407AFF
PreeditColorPostCaret=#EB0081FF
BorderColor=#FFFFFFFF
DividerColor=#FFFFFFFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
