[LightMode]
OverrideDefault=True
HighlightColor=#0A3AFAFF
HighlightHoverColor=#0A3AFAFF
HighlightTextColor=#FFFFFFE5
HighlightTextPressColor=#FFFFFFE5
HighlightLabelColor=#FFFFFFE5
HighlightCommentColor=#C5C5C5FF
HighlightMarkColor=#FFFFFFE5
PanelColor=#242424FF
TextColor=#FFFFFF99
LabelColor=#FFFFFF85
CommentColor=#FFFFFF55
PagingButtonColor=#FFFFFF99
DisabledPagingButtonColor=#FFFFFF55
AuxColor=#FFFFFFE5
PreeditColorPreCaret=#FFFFFFE5
PreeditColorCaret=#FFFFFFE5
PreeditColorPostCaret=#FFFFFFE5
BorderColor=#E0E0E0FF
DividerColor=#E0E0E0FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#0A3AFAFF
HighlightHoverColor=#0A3AFAFF
HighlightTextColor=#FFFFFFE5
HighlightTextPressColor=#FFFFFFE5
HighlightLabelColor=#FFFFFFE5
HighlightCommentColor=#C5C5C5FF
HighlightMarkColor=#FFFFFFE5
PanelColor=#242424FF
TextColor=#FFFFFF99
LabelColor=#FFFFFF85
CommentColor=#FFFFFF55
PagingButtonColor=#FFFFFF99
DisabledPagingButtonColor=#FFFFFF55
AuxColor=#FFFFFFE5
PreeditColorPreCaret=#FFFFFFE5
PreeditColorCaret=#FFFFFFE5
PreeditColorPostCaret=#FFFFFFE5
BorderColor=#E0E0E0FF
DividerColor=#E0E0E0FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
