[LightMode]
OverrideDefault=True
HighlightColor=#636F67FF
HighlightHoverColor=#636F67FF
HighlightTextColor=#DCFEABFF
HighlightTextPressColor=#DCFEABFF
HighlightLabelColor=#DCFEABFF
HighlightCommentColor=#DCFEABFF
HighlightMarkColor=#DCFEABFF
PanelColor=#0D1B0AFF
TextColor=#DCFEABFF
LabelColor=#DCFEABFF
CommentColor=#FBFDFCFF
PagingButtonColor=#DCFEABFF
DisabledPagingButtonColor=#FBFDFCFF
AuxColor=#FCFDFBFF
PreeditColorPreCaret=#FCFDFBFF
PreeditColorCaret=#DCFEABFF
PreeditColorPostCaret=#FCFDFBFF
BorderColor=#83AD4BFF
DividerColor=#83AD4BFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#636F67FF
HighlightHoverColor=#636F67FF
HighlightTextColor=#DCFEABFF
HighlightTextPressColor=#DCFEABFF
HighlightLabelColor=#DCFEABFF
HighlightCommentColor=#DCFEABFF
HighlightMarkColor=#DCFEABFF
PanelColor=#0D1B0AFF
TextColor=#DCFEABFF
LabelColor=#DCFEABFF
CommentColor=#FBFDFCFF
PagingButtonColor=#DCFEABFF
DisabledPagingButtonColor=#FBFDFCFF
AuxColor=#FCFDFBFF
PreeditColorPreCaret=#FCFDFBFF
PreeditColorCaret=#DCFEABFF
PreeditColorPostCaret=#FCFDFBFF
BorderColor=#83AD4BFF
DividerColor=#83AD4BFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
