[LightMode]
OverrideDefault=True
HighlightColor=#FF79C6FF
HighlightHoverColor=#FF79C6FF
HighlightTextColor=#F8F8F2FF
HighlightTextPressColor=#F8F8F2FF
HighlightLabelColor=#F8F8F2FF
HighlightCommentColor=#002B36FF
HighlightMarkColor=#F8F8F2FF
PanelColor=#282A36FF
TextColor=#BD93F9FF
LabelColor=#BD93F9FF
CommentColor=#8BE9FDFF
PagingButtonColor=#BD93F9FF
DisabledPagingButtonColor=#8BE9FDFF
AuxColor=#44475AFF
PreeditColorPreCaret=#44475AFF
PreeditColorCaret=#F8F8F2FF
PreeditColorPostCaret=#44475AFF
BorderColor=#282A36FF
DividerColor=#282A36FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#FF79C6FF
HighlightHoverColor=#FF79C6FF
HighlightTextColor=#F8F8F2FF
HighlightTextPressColor=#F8F8F2FF
HighlightLabelColor=#F8F8F2FF
HighlightCommentColor=#002B36FF
HighlightMarkColor=#F8F8F2FF
PanelColor=#282A36FF
TextColor=#BD93F9FF
LabelColor=#BD93F9FF
CommentColor=#8BE9FDFF
PagingButtonColor=#BD93F9FF
DisabledPagingButtonColor=#8BE9FDFF
AuxColor=#44475AFF
PreeditColorPreCaret=#44475AFF
PreeditColorCaret=#F8F8F2FF
PreeditColorPostCaret=#44475AFF
BorderColor=#282A36FF
DividerColor=#282A36FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
