[LightMode]
OverrideDefault=True
HighlightColor=#D33682FF
HighlightHoverColor=#D33682FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#002B36FF
HighlightMarkColor=#FFFFFFFF
PanelColor=#002B36FF
TextColor=#839496FF
LabelColor=#839496FF
CommentColor=#2AA198C0
PagingButtonColor=#839496FF
DisabledPagingButtonColor=#2AA198C0
AuxColor=#2AA198FF
PreeditColorPreCaret=#2AA198FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#2AA198FF
BorderColor=#002B36FF
DividerColor=#002B36FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#D33682FF
HighlightHoverColor=#D33682FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#002B36FF
HighlightMarkColor=#FFFFFFFF
PanelColor=#002B36FF
TextColor=#839496FF
LabelColor=#839496FF
CommentColor=#2AA198C0
PagingButtonColor=#839496FF
DisabledPagingButtonColor=#2AA198C0
AuxColor=#2AA198FF
PreeditColorPreCaret=#2AA198FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#2AA198FF
BorderColor=#002B36FF
DividerColor=#002B36FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
