[LightMode]
OverrideDefault=True
HighlightColor=#009FE8FF
HighlightHoverColor=#009FE8FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#000000FF
TextColor=#FFFFFFFF
LabelColor=#FFFFFFFF
CommentColor=#FFFFFFFF
PagingButtonColor=#FFFFFFFF
DisabledPagingButtonColor=#FFFFFFFF
AuxColor=#FFFFFFFF
PreeditColorPreCaret=#FFFFFFFF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#FFFFFFFF
BorderColor=#000000FF
DividerColor=#000000FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#009FE8FF
HighlightHoverColor=#009FE8FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#000000FF
TextColor=#FFFFFFFF
LabelColor=#FFFFFFFF
CommentColor=#FFFFFFFF
PagingButtonColor=#FFFFFFFF
DisabledPagingButtonColor=#FFFFFFFF
AuxColor=#FFFFFFFF
PreeditColorPreCaret=#FFFFFFFF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#FFFFFFFF
BorderColor=#000000FF
DividerColor=#000000FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
