[LightMode]
OverrideDefault=True
HighlightColor=#DD4118FF
HighlightHoverColor=#DD4118FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#100F12FF
TextColor=#8F755CFF
LabelColor=#8F755CFF
CommentColor=#8F755CFF
PagingButtonColor=#8F755CFF
DisabledPagingButtonColor=#8F755CFF
AuxColor=#DD4118FF
PreeditColorPreCaret=#DD4118FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#DD4118FF
BorderColor=#100F12FF
DividerColor=#100F12FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#DD4118FF
HighlightHoverColor=#DD4118FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#100F12FF
TextColor=#8F755CFF
LabelColor=#8F755CFF
CommentColor=#8F755CFF
PagingButtonColor=#8F755CFF
DisabledPagingButtonColor=#8F755CFF
AuxColor=#DD4118FF
PreeditColorPreCaret=#DD4118FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#DD4118FF
BorderColor=#100F12FF
DividerColor=#100F12FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
