[LightMode]
OverrideDefault=True
HighlightColor=#2559D0FF
HighlightHoverColor=#2559D0FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#808080FF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#000000D8
LabelColor=#7F7F7FFF
CommentColor=#0000003F
PagingButtonColor=#000000D8
DisabledPagingButtonColor=#0000003F
AuxColor=#000000D8
PreeditColorPreCaret=#000000D8
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#000000D8
BorderColor=#FFFFFFFF
DividerColor=#FFFFFFFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#2559D0FF
HighlightHoverColor=#2559D0FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#808080FF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#000000D8
LabelColor=#7F7F7FFF
CommentColor=#0000003F
PagingButtonColor=#000000D8
DisabledPagingButtonColor=#0000003F
AuxColor=#000000D8
PreeditColorPreCaret=#000000D8
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#000000D8
BorderColor=#FFFFFFFF
DividerColor=#FFFFFFFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
