[LightMode]
OverrideDefault=True
HighlightColor=#1AC0C6FF
HighlightHoverColor=#1AC0C6FF
HighlightTextColor=#EFEFEFFF
HighlightTextPressColor=#EFEFEFFF
HighlightLabelColor=#EFEFEFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#EFEFEFFF
PanelColor=#424242FF
TextColor=#EFEFEFFF
LabelColor=#EFEFEFFF
CommentColor=#EFEFEFFF
PagingButtonColor=#EFEFEFFF
DisabledPagingButtonColor=#EFEFEFFF
AuxColor=#1AC0C6FF
PreeditColorPreCaret=#1AC0C6FF
PreeditColorCaret=#EFEFEFFF
PreeditColorPostCaret=#1AC0C6FF
BorderColor=#424242FF
DividerColor=#424242FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#1AC0C6FF
HighlightHoverColor=#1AC0C6FF
HighlightTextColor=#EFEFEFFF
HighlightTextPressColor=#EFEFEFFF
HighlightLabelColor=#EFEFEFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#EFEFEFFF
PanelColor=#424242FF
TextColor=#EFEFEFFF
LabelColor=#EFEFEFFF
CommentColor=#EFEFEFFF
PagingButtonColor=#EFEFEFFF
DisabledPagingButtonColor=#EFEFEFFF
AuxColor=#1AC0C6FF
PreeditColorPreCaret=#1AC0C6FF
PreeditColorCaret=#EFEFEFFF
PreeditColorPostCaret=#1AC0C6FF
BorderColor=#424242FF
DividerColor=#424242FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
