[LightMode]
OverrideDefault=True
HighlightColor=#288C44FF
HighlightHoverColor=#288C44FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#EEEEEFFF
TextColor=#8DC21FFF
LabelColor=#B5F05BFF
CommentColor=#8DC21FFF
PagingButtonColor=#8DC21FFF
DisabledPagingButtonColor=#8DC21FFF
AuxColor=#FFFFFFFF
PreeditColorPreCaret=#FFFFFFFF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#FFFFFFFF
BorderColor=#EEEEEFFF
DividerColor=#EEEEEFFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#288C44FF
HighlightHoverColor=#288C44FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#EEEEEFFF
TextColor=#8DC21FFF
LabelColor=#B5F05BFF
CommentColor=#8DC21FFF
PagingButtonColor=#8DC21FFF
DisabledPagingButtonColor=#8DC21FFF
AuxColor=#FFFFFFFF
PreeditColorPreCaret=#FFFFFFFF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#FFFFFFFF
BorderColor=#EEEEEFFF
DividerColor=#EEEEEFFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
