[LightMode]
OverrideDefault=True
HighlightColor=#2072A3FF
HighlightHoverColor=#2072A3FF
HighlightTextColor=#F2F2F2FF
HighlightTextPressColor=#F2F2F2FF
HighlightLabelColor=#F2F2F2FF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#F2F2F2FF
PanelColor=#1F1F1FFF
TextColor=#F2F2F2FF
LabelColor=#888888FF
CommentColor=#888888FF
PagingButtonColor=#F2F2F2FF
DisabledPagingButtonColor=#888888FF
AuxColor=#FFFFFFFF
PreeditColorPreCaret=#FFFFFFFF
PreeditColorCaret=#F2F2F2FF
PreeditColorPostCaret=#FFFFFFFF
BorderColor=#2072A3FF
DividerColor=#2072A3FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#2072A3FF
HighlightHoverColor=#2072A3FF
HighlightTextColor=#F2F2F2FF
HighlightTextPressColor=#F2F2F2FF
HighlightLabelColor=#F2F2F2FF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#F2F2F2FF
PanelColor=#1F1F1FFF
TextColor=#F2F2F2FF
LabelColor=#888888FF
CommentColor=#888888FF
PagingButtonColor=#F2F2F2FF
DisabledPagingButtonColor=#888888FF
AuxColor=#FFFFFFFF
PreeditColorPreCaret=#FFFFFFFF
PreeditColorCaret=#F2F2F2FF
PreeditColorPostCaret=#FFFFFFFF
BorderColor=#2072A3FF
DividerColor=#2072A3FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
