[LightMode]
OverrideDefault=True
HighlightColor=#163540FF
HighlightHoverColor=#163540FF
HighlightTextColor=#529F98FF
HighlightTextPressColor=#529F98FF
HighlightLabelColor=#529F98FF
HighlightCommentColor=#899928FF
HighlightMarkColor=#529F98FF
PanelColor=#0A2A35F0
TextColor=#FF8973FF
LabelColor=#F48D47FF
CommentColor=#FF8AC3FF
PagingButtonColor=#FF8973FF
DisabledPagingButtonColor=#FF8AC3FF
AuxColor=#6D70BEFF
PreeditColorPreCaret=#6D70BEFF
PreeditColorCaret=#529F98FF
PreeditColorPostCaret=#6D70BEFF
BorderColor=#001F2AFF
DividerColor=#001F2AFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#163540FF
HighlightHoverColor=#163540FF
HighlightTextColor=#529F98FF
HighlightTextPressColor=#529F98FF
HighlightLabelColor=#529F98FF
HighlightCommentColor=#899928FF
HighlightMarkColor=#529F98FF
PanelColor=#0A2A35F0
TextColor=#FF8973FF
LabelColor=#F48D47FF
CommentColor=#FF8AC3FF
PagingButtonColor=#FF8973FF
DisabledPagingButtonColor=#FF8AC3FF
AuxColor=#6D70BEFF
PreeditColorPreCaret=#6D70BEFF
PreeditColorCaret=#529F98FF
PreeditColorPostCaret=#6D70BEFF
BorderColor=#001F2AFF
DividerColor=#001F2AFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
