[LightMode]
OverrideDefault=True
HighlightColor=#005DCBFF
HighlightHoverColor=#005DCBFF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#202325FF
TextColor=#DDDDDEFF
LabelColor=#858788FF
CommentColor=#DDDDDEFF
PagingButtonColor=#DDDDDEFF
DisabledPagingButtonColor=#DDDDDEFF
AuxColor=#DDDDDEFF
PreeditColorPreCaret=#DDDDDEFF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#DDDDDEFF
BorderColor=#020202FF
DividerColor=#020202FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#005DCBFF
HighlightHoverColor=#005DCBFF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#202325FF
TextColor=#DDDDDEFF
LabelColor=#858788FF
CommentColor=#DDDDDEFF
PagingButtonColor=#DDDDDEFF
DisabledPagingButtonColor=#DDDDDEFF
AuxColor=#DDDDDEFF
PreeditColorPreCaret=#DDDDDEFF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#DDDDDEFF
BorderColor=#020202FF
DividerColor=#020202FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
