[LightMode]
OverrideDefault=True
HighlightColor=#FF79C6FF
HighlightHoverColor=#FF79C6FF
HighlightTextColor=#F8F8F2FF
HighlightTextPressColor=#F8F8F2FF
HighlightLabelColor=#F8F8F2FF
HighlightCommentColor=#002B36FF
HighlightMarkColor=#F8F8F2FF
PanelColor=#F8F8F2FF
TextColor=#282A36FF
LabelColor=#282A36FF
CommentColor=#44475AFF
PagingButtonColor=#282A36FF
DisabledPagingButtonColor=#44475AFF
AuxColor=#282A36FF
PreeditColorPreCaret=#282A36FF
PreeditColorCaret=#F8F8F2FF
PreeditColorPostCaret=#282A36FF
BorderColor=#F8F8F2FF
DividerColor=#F8F8F2FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#FF79C6FF
HighlightHoverColor=#FF79C6FF
HighlightTextColor=#F8F8F2FF
HighlightTextPressColor=#F8F8F2FF
HighlightLabelColor=#F8F8F2FF
HighlightCommentColor=#002B36FF
HighlightMarkColor=#F8F8F2FF
PanelColor=#F8F8F2FF
TextColor=#282A36FF
LabelColor=#282A36FF
CommentColor=#44475AFF
PagingButtonColor=#282A36FF
DisabledPagingButtonColor=#44475AFF
AuxColor=#282A36FF
PreeditColorPreCaret=#282A36FF
PreeditColorCaret=#F8F8F2FF
PreeditColorPostCaret=#282A36FF
BorderColor=#F8F8F2FF
DividerColor=#F8F8F2FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
