[LightMode]
OverrideDefault=True
HighlightColor=#3D4753FF
HighlightHoverColor=#3D4753FF
HighlightTextColor=#FB96AEFF
HighlightTextPressColor=#FB96AEFF
HighlightLabelColor=#FB96AEFF
HighlightCommentColor=#A6CA82FF
HighlightMarkColor=#FB96AEFF
PanelColor=#3D4753FF
TextColor=#86F6CEFF
LabelColor=#86F6CEFF
CommentColor=#86F6CEFF
PagingButtonColor=#86F6CEFF
DisabledPagingButtonColor=#86F6CEFF
AuxColor=#A6CA82FF
PreeditColorPreCaret=#A6CA82FF
PreeditColorCaret=#FB96AEFF
PreeditColorPostCaret=#A6CA82FF
BorderColor=#3D4753FF
DividerColor=#3D4753FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#3D4753FF
HighlightHoverColor=#3D4753FF
HighlightTextColor=#FB96AEFF
HighlightTextPressColor=#FB96AEFF
HighlightLabelColor=#FB96AEFF
HighlightCommentColor=#A6CA82FF
HighlightMarkColor=#FB96AEFF
PanelColor=#3D4753FF
TextColor=#86F6CEFF
LabelColor=#86F6CEFF
CommentColor=#86F6CEFF
PagingButtonColor=#86F6CEFF
DisabledPagingButtonColor=#86F6CEFF
AuxColor=#A6CA82FF
PreeditColorPreCaret=#A6CA82FF
PreeditColorCaret=#FB96AEFF
PreeditColorPostCaret=#A6CA82FF
BorderColor=#3D4753FF
DividerColor=#3D4753FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
