[LightMode]
OverrideDefault=True
HighlightColor=#00000040
HighlightHoverColor=#00000040
HighlightTextColor=#FFFF7FFF
HighlightTextPressColor=#FFFF7FFF
HighlightLabelColor=#FFFF7FFF
HighlightCommentColor=#9D9C44FF
HighlightMarkColor=#FFFF7FFF
PanelColor=#000000DD
TextColor=#EEEEECFF
LabelColor=#EEEEECFF
CommentColor=#A5A5A5FF
PagingButtonColor=#EEEEECFF
DisabledPagingButtonColor=#A5A5A5FF
AuxColor=#FFFF7FFF
PreeditColorPreCaret=#FFFF7FFF
PreeditColorCaret=#FFFF7FFF
PreeditColorPostCaret=#FFFF7FFF
BorderColor=#000000DD
DividerColor=#000000DD

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#00000040
HighlightHoverColor=#00000040
HighlightTextColor=#FFFF7FFF
HighlightTextPressColor=#FFFF7FFF
HighlightLabelColor=#FFFF7FFF
HighlightCommentColor=#9D9C44FF
HighlightMarkColor=#FFFF7FFF
PanelColor=#000000DD
TextColor=#EEEEECFF
LabelColor=#EEEEECFF
CommentColor=#A5A5A5FF
PagingButtonColor=#EEEEECFF
DisabledPagingButtonColor=#A5A5A5FF
AuxColor=#FFFF7FFF
PreeditColorPreCaret=#FFFF7FFF
PreeditColorCaret=#FFFF7FFF
PreeditColorPostCaret=#FFFF7FFF
BorderColor=#000000DD
DividerColor=#000000DD

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
