[LightMode]
OverrideDefault=True
HighlightColor=#F0F0F0FF
HighlightHoverColor=#F0F0F0FF
HighlightTextColor=#0A0A0AFF
HighlightTextPressColor=#0A0A0AFF
HighlightLabelColor=#1A1A1AFF
HighlightCommentColor=#1A1A1AFF
HighlightMarkColor=#0A0A0AFF
PanelColor=#F9F9F9FF
TextColor=#000000FF
LabelColor=#1A1A1AFF
CommentColor=#666666FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#666666FF
AuxColor=#1A1A1AFF
PreeditColorPreCaret=#1A1A1AFF
PreeditColorCaret=#0A0A0AFF
PreeditColorPostCaret=#1A1A1AFF
BorderColor=#F0F0F010
DividerColor=#F0F0F010

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#F0F0F0FF
HighlightHoverColor=#F0F0F0FF
HighlightTextColor=#0A0A0AFF
HighlightTextPressColor=#0A0A0AFF
HighlightLabelColor=#1A1A1AFF
HighlightCommentColor=#1A1A1AFF
HighlightMarkColor=#0A0A0AFF
PanelColor=#F9F9F9FF
TextColor=#000000FF
LabelColor=#1A1A1AFF
CommentColor=#666666FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#666666FF
AuxColor=#1A1A1AFF
PreeditColorPreCaret=#1A1A1AFF
PreeditColorCaret=#0A0A0AFF
PreeditColorPostCaret=#1A1A1AFF
BorderColor=#F0F0F010
DividerColor=#F0F0F010

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
