[LightMode]
OverrideDefault=True
HighlightColor=#33CCFFFF
HighlightHoverColor=#33CCFFFF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#EFEFEFFF
TextColor=#595757FF
LabelColor=#C8C9CAFF
CommentColor=#C8C9CAFF
PagingButtonColor=#595757FF
DisabledPagingButtonColor=#C8C9CAFF
AuxColor=#33CCFFFF
PreeditColorPreCaret=#33CCFFFF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#33CCFFFF
BorderColor=#EFEFEFFF
DividerColor=#EFEFEFFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#33CCFFFF
HighlightHoverColor=#33CCFFFF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#EFEFEFFF
TextColor=#595757FF
LabelColor=#C8C9CAFF
CommentColor=#C8C9CAFF
PagingButtonColor=#595757FF
DisabledPagingButtonColor=#C8C9CAFF
AuxColor=#33CCFFFF
PreeditColorPreCaret=#33CCFFFF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#33CCFFFF
BorderColor=#EFEFEFFF
DividerColor=#EFEFEFFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
