[LightMode]
OverrideDefault=True
HighlightColor=#3975CEFF
HighlightHoverColor=#3975CEFF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#B0C6EBFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#000000FF
LabelColor=#000000FF
CommentColor=#6D6D6DFF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#6D6D6DFF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#000000FF
BorderColor=#E2E2E2FF
DividerColor=#E2E2E2FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#3975CEFF
HighlightHoverColor=#3975CEFF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#B0C6EBFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#000000FF
LabelColor=#000000FF
CommentColor=#6D6D6DFF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#6D6D6DFF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#000000FF
BorderColor=#E2E2E2FF
DividerColor=#E2E2E2FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
