[LightMode]
OverrideDefault=True
HighlightColor=#009FE8FF
HighlightHoverColor=#009FE8FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#666666FF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#000000FF
LabelColor=#666666FF
CommentColor=#666666FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#666666FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#000000FF
BorderColor=#009FE8FF
DividerColor=#009FE8FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#009FE8FF
HighlightHoverColor=#009FE8FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#666666FF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#000000FF
LabelColor=#666666FF
CommentColor=#666666FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#666666FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#000000FF
BorderColor=#009FE8FF
DividerColor=#009FE8FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
