[LightMode]
OverrideDefault=True
HighlightColor=#FFFFFFFF
HighlightHoverColor=#FFFFFFFF
HighlightTextColor=#000000FF
HighlightTextPressColor=#000000FF
HighlightLabelColor=#000000FF
HighlightCommentColor=#000000FF
HighlightMarkColor=#000000FF
PanelColor=#FFFFFFFF
TextColor=#000000FF
LabelColor=#000000FF
CommentColor=#000000FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#000000FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#000000FF
PreeditColorPostCaret=#000000FF
BorderColor=#FFFFFFFF
DividerColor=#FFFFFFFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#FFFFFFFF
HighlightHoverColor=#FFFFFFFF
HighlightTextColor=#000000FF
HighlightTextPressColor=#000000FF
HighlightLabelColor=#000000FF
HighlightCommentColor=#000000FF
HighlightMarkColor=#000000FF
PanelColor=#FFFFFFFF
TextColor=#000000FF
LabelColor=#000000FF
CommentColor=#000000FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#000000FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#000000FF
PreeditColorPostCaret=#000000FF
BorderColor=#FFFFFFFF
DividerColor=#FFFFFFFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
