[LightMode]
OverrideDefault=True
HighlightColor=#DD4B39FF
HighlightHoverColor=#DD4B39FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#DD4B39FF
LabelColor=#C8C9CAFF
CommentColor=#C8C9CAFF
PagingButtonColor=#DD4B39FF
DisabledPagingButtonColor=#C8C9CAFF
AuxColor=#DD4B39FF
PreeditColorPreCaret=#DD4B39FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#DD4B39FF
BorderColor=#DD4B39FF
DividerColor=#DD4B39FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#DD4B39FF
HighlightHoverColor=#DD4B39FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#DD4B39FF
LabelColor=#C8C9CAFF
CommentColor=#C8C9CAFF
PagingButtonColor=#DD4B39FF
DisabledPagingButtonColor=#C8C9CAFF
AuxColor=#DD4B39FF
PreeditColorPreCaret=#DD4B39FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#DD4B39FF
BorderColor=#DD4B39FF
DividerColor=#DD4B39FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
