[LightMode]
OverrideDefault=True
HighlightColor=#2AA198FF
HighlightHoverColor=#2AA198FF
HighlightTextColor=#EEE8D5FF
HighlightTextPressColor=#EEE8D5FF
HighlightLabelColor=#EEE8D5FF
HighlightCommentColor=#EEE8D5FF
HighlightMarkColor=#EEE8D5FF
PanelColor=#FDF6E3FF
TextColor=#657B83FF
LabelColor=#93A1A1FF
CommentColor=#268BD2FF
PagingButtonColor=#657B83FF
DisabledPagingButtonColor=#268BD2FF
AuxColor=#839496FF
PreeditColorPreCaret=#839496FF
PreeditColorCaret=#EEE8D5FF
PreeditColorPostCaret=#839496FF
BorderColor=#EEE8D5FF
DividerColor=#EEE8D5FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#2AA198FF
HighlightHoverColor=#2AA198FF
HighlightTextColor=#EEE8D5FF
HighlightTextPressColor=#EEE8D5FF
HighlightLabelColor=#EEE8D5FF
HighlightCommentColor=#EEE8D5FF
HighlightMarkColor=#EEE8D5FF
PanelColor=#FDF6E3FF
TextColor=#657B83FF
LabelColor=#93A1A1FF
CommentColor=#268BD2FF
PagingButtonColor=#657B83FF
DisabledPagingButtonColor=#268BD2FF
AuxColor=#839496FF
PreeditColorPreCaret=#839496FF
PreeditColorCaret=#EEE8D5FF
PreeditColorPostCaret=#839496FF
BorderColor=#EEE8D5FF
DividerColor=#EEE8D5FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
