[LightMode]
OverrideDefault=True
HighlightColor=#E4F0FFFF
HighlightHoverColor=#E4F0FFFF
HighlightTextColor=#000000FF
HighlightTextPressColor=#000000FF
HighlightLabelColor=#000000FF
HighlightCommentColor=#9E9E9EFF
HighlightMarkColor=#000000FF
PanelColor=#FFFFFFEE
TextColor=#555555FF
LabelColor=#CBCBCBFF
CommentColor=#999999FF
PagingButtonColor=#555555FF
DisabledPagingButtonColor=#999999FF
AuxColor=#9E9E9EFF
PreeditColorPreCaret=#9E9E9EFF
PreeditColorCaret=#000000FF
PreeditColorPostCaret=#9E9E9EFF
BorderColor=#93B6E0FF
DividerColor=#93B6E0FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#E4F0FFFF
HighlightHoverColor=#E4F0FFFF
HighlightTextColor=#000000FF
HighlightTextPressColor=#000000FF
HighlightLabelColor=#000000FF
HighlightCommentColor=#9E9E9EFF
HighlightMarkColor=#000000FF
PanelColor=#FFFFFFEE
TextColor=#555555FF
LabelColor=#CBCBCBFF
CommentColor=#999999FF
PagingButtonColor=#555555FF
DisabledPagingButtonColor=#999999FF
AuxColor=#9E9E9EFF
PreeditColorPreCaret=#9E9E9EFF
PreeditColorCaret=#000000FF
PreeditColorPostCaret=#9E9E9EFF
BorderColor=#93B6E0FF
DividerColor=#93B6E0FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
