[LightMode]
OverrideDefault=True
HighlightColor=#EEEEEEFF
HighlightHoverColor=#EEEEEEFF
HighlightTextColor=#1589C9FF
HighlightTextPressColor=#1589C9FF
HighlightLabelColor=#1589C9FF
HighlightCommentColor=#1589C9FF
HighlightMarkColor=#1589C9FF
PanelColor=#EEEEEEFF
TextColor=#000000FF
LabelColor=#888888FF
CommentColor=#808080FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#808080FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#1589C9FF
PreeditColorPostCaret=#000000FF
BorderColor=#EEEEEEFF
DividerColor=#EEEEEEFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#EEEEEEFF
HighlightHoverColor=#EEEEEEFF
HighlightTextColor=#1589C9FF
HighlightTextPressColor=#1589C9FF
HighlightLabelColor=#1589C9FF
HighlightCommentColor=#1589C9FF
HighlightMarkColor=#1589C9FF
PanelColor=#EEEEEEFF
TextColor=#000000FF
LabelColor=#888888FF
CommentColor=#808080FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#808080FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#1589C9FF
PreeditColorPostCaret=#000000FF
BorderColor=#EEEEEEFF
DividerColor=#EEEEEEFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
