[LightMode]
OverrideDefault=True
HighlightColor=#314259FF
HighlightHoverColor=#314259FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#A9A7A7FF
HighlightMarkColor=#FFFFFFFF
PanelColor=#171614FF
TextColor=#FFFFFFFF
LabelColor=#FFFFFFFF
CommentColor=#A9A7A7FF
PagingButtonColor=#FFFFFFFF
DisabledPagingButtonColor=#A9A7A7FF
AuxColor=#D1CFC9FF
PreeditColorPreCaret=#D1CFC9FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#D1CFC9FF
BorderColor=#383635FF
DividerColor=#383635FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#314259FF
HighlightHoverColor=#314259FF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#A9A7A7FF
HighlightMarkColor=#FFFFFFFF
PanelColor=#171614FF
TextColor=#FFFFFFFF
LabelColor=#FFFFFFFF
CommentColor=#A9A7A7FF
PagingButtonColor=#FFFFFFFF
DisabledPagingButtonColor=#A9A7A7FF
AuxColor=#D1CFC9FF
PreeditColorPreCaret=#D1CFC9FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#D1CFC9FF
BorderColor=#383635FF
DividerColor=#383635FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
