[LightMode]
OverrideDefault=True
HighlightColor=#CAE682FF
HighlightHoverColor=#CAE682FF
HighlightTextColor=#000000FF
HighlightTextPressColor=#000000FF
HighlightLabelColor=#000000FF
HighlightCommentColor=#343D20BB
HighlightMarkColor=#000000FF
PanelColor=#303030EE
TextColor=#F6F3E8FF
LabelColor=#F6F3E8FF
CommentColor=#CAE682BB
PagingButtonColor=#F6F3E8FF
DisabledPagingButtonColor=#CAE682BB
AuxColor=#CAE682FF
PreeditColorPreCaret=#CAE682FF
PreeditColorCaret=#000000FF
PreeditColorPostCaret=#CAE682FF
BorderColor=#303030EE
DividerColor=#303030EE

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#CAE682FF
HighlightHoverColor=#CAE682FF
HighlightTextColor=#000000FF
HighlightTextPressColor=#000000FF
HighlightLabelColor=#000000FF
HighlightCommentColor=#343D20BB
HighlightMarkColor=#000000FF
PanelColor=#303030EE
TextColor=#F6F3E8FF
LabelColor=#F6F3E8FF
CommentColor=#CAE682BB
PagingButtonColor=#F6F3E8FF
DisabledPagingButtonColor=#CAE682BB
AuxColor=#CAE682FF
PreeditColorPreCaret=#CAE682FF
PreeditColorCaret=#000000FF
PreeditColorPostCaret=#CAE682FF
BorderColor=#303030EE
DividerColor=#303030EE

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
