[LightMode]
OverrideDefault=True
HighlightColor=#F9EDEDFF
HighlightHoverColor=#F9EDEDFF
HighlightTextColor=#FA114FFF
HighlightTextPressColor=#FA114FFF
HighlightLabelColor=#FA114FFF
HighlightCommentColor=#389CF1FF
HighlightMarkColor=#FA114FFF
PanelColor=#F6F4F4FF
TextColor=#383838FF
LabelColor=#AAAAAAFF
CommentColor=#7B8087FF
PagingButtonColor=#383838FF
DisabledPagingButtonColor=#7B8087FF
AuxColor=#938E8EFF
PreeditColorPreCaret=#938E8EFF
PreeditColorCaret=#FA114FFF
PreeditColorPostCaret=#938E8EFF
BorderColor=#FFFFFFFF
DividerColor=#FFFFFFFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#F9EDEDFF
HighlightHoverColor=#F9EDEDFF
HighlightTextColor=#FA114FFF
HighlightTextPressColor=#FA114FFF
HighlightLabelColor=#FA114FFF
HighlightCommentColor=#389CF1FF
HighlightMarkColor=#FA114FFF
PanelColor=#F6F4F4FF
TextColor=#383838FF
LabelColor=#AAAAAAFF
CommentColor=#7B8087FF
PagingButtonColor=#383838FF
DisabledPagingButtonColor=#7B8087FF
AuxColor=#938E8EFF
PreeditColorPreCaret=#938E8EFF
PreeditColorCaret=#FA114FFF
PreeditColorPostCaret=#938E8EFF
BorderColor=#FFFFFFFF
DividerColor=#FFFFFFFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
