[LightMode]
OverrideDefault=True
HighlightColor=#298FCCFF
HighlightHoverColor=#298FCCFF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#000000FF
LabelColor=#888888FF
CommentColor=#888888FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#888888FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#000000FF
BorderColor=#FFFFFFFF
DividerColor=#FFFFFFFF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#298FCCFF
HighlightHoverColor=#298FCCFF
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#FFFFFFFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#FFFFFFFF
TextColor=#000000FF
LabelColor=#888888FF
CommentColor=#888888FF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#888888FF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#000000FF
BorderColor=#FFFFFFFF
DividerColor=#FFFFFFFF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
