[LightMode]
OverrideDefault=True
HighlightColor=#D8DEE9FF
HighlightHoverColor=#D8DEE9FF
HighlightTextColor=#5E81ACFF
HighlightTextPressColor=#5E81ACFF
HighlightLabelColor=#5E81ACFF
HighlightCommentColor=#5E81ACFF
HighlightMarkColor=#5E81ACFF
PanelColor=#ECEFF4FF
TextColor=#81A1C1FF
LabelColor=#81A1C1FF
CommentColor=#88C0D0FF
PagingButtonColor=#81A1C1FF
DisabledPagingButtonColor=#88C0D0FF
AuxColor=#B48EADFF
PreeditColorPreCaret=#B48EADFF
PreeditColorCaret=#5E81ACFF
PreeditColorPostCaret=#B48EADFF
BorderColor=#ECEFF4FF
DividerColor=#ECEFF4FF

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#D8DEE9FF
HighlightHoverColor=#D8DEE9FF
HighlightTextColor=#5E81ACFF
HighlightTextPressColor=#5E81ACFF
HighlightLabelColor=#5E81ACFF
HighlightCommentColor=#5E81ACFF
HighlightMarkColor=#5E81ACFF
PanelColor=#ECEFF4FF
TextColor=#81A1C1FF
LabelColor=#81A1C1FF
CommentColor=#88C0D0FF
PagingButtonColor=#81A1C1FF
DisabledPagingButtonColor=#88C0D0FF
AuxColor=#B48EADFF
PreeditColorPreCaret=#B48EADFF
PreeditColorCaret=#5E81ACFF
PreeditColorPostCaret=#B48EADFF
BorderColor=#ECEFF4FF
DividerColor=#ECEFF4FF

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
