[LightMode]
OverrideDefault=True
HighlightColor=#0A3AFAEE
HighlightHoverColor=#0A3AFAEE
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#9DACFCFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#EEEEECEE
TextColor=#000000FF
LabelColor=#000000FF
CommentColor=#5A5A5AFF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#5A5A5AFF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#000000FF
BorderColor=#EEEEECEE
DividerColor=#EEEEECEE

[DarkMode]
OverrideDefault=True
SameWithLightMode=True
HighlightColor=#0A3AFAEE
HighlightHoverColor=#0A3AFAEE
HighlightTextColor=#FFFFFFFF
HighlightTextPressColor=#FFFFFFFF
HighlightLabelColor=#FFFFFFFF
HighlightCommentColor=#9DACFCFF
HighlightMarkColor=#FFFFFFFF
PanelColor=#EEEEECEE
TextColor=#000000FF
LabelColor=#000000FF
CommentColor=#5A5A5AFF
PagingButtonColor=#000000FF
DisabledPagingButtonColor=#5A5A5AFF
AuxColor=#000000FF
PreeditColorPreCaret=#000000FF
PreeditColorCaret=#FFFFFFFF
PreeditColorPostCaret=#000000FF
BorderColor=#EEEEECEE
DividerColor=#EEEEECEE

[Typography]
Layout=Vertical
WritingMode=Horizontal top-bottom
TypographyAwarenessForIM=True

[Background]
KeepPanelColorWhenHasImage=True
Blur=System
Shadow=True

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=8
Margin=0
HighlightRadius=6
TopPadding=5
RightPadding=7
BottomPadding=5
LeftPadding=7
LabelTextGap=6
VerticalMinWidth=200
HorizontalDividerWidth=1
