[Metadata]
Name=少数派红／AppSo Red
Version=1
Author=Astrian Zheng
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#F2C3C5FF
HighlightColor=#FFFFFFFF
HighlightBackgroundColor=#C82428FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#F2C3C5FF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#FFFFFFFF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#C82428FF
BorderColor=#C82428FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#C82428FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#F2C3C5FF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#C82428FF
BorderColor=#C82428FF
BorderWidth=1

[Menu/Highlight]
Color=#C82428FF

[Menu/Separator]
Color=#C82428FF
