[Metadata]
Name=Win11Light
Version=1
Author=eosphoros desktop theme collection
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#000000FF
HighlightColor=#1A1A1AFF
HighlightBackgroundColor=#F0F0F0FF
HighlightCandidateColor=#0A0A0AFF
CandidateLabelColor=#1A1A1AFF
HighlightCandidateLabelColor=#1A1A1AFF
CandidateCommentColor=#666666FF
HighlightCandidateCommentColor=#1A1A1AFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#F9F9F9FF
BorderColor=#F0F0F010
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#F0F0F0FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#000000FF
HighlightCandidateColor=#0A0A0AFF

[Menu/Background]
Color=#F9F9F9FF
BorderColor=#F0F0F010
BorderWidth=1

[Menu/Highlight]
Color=#F0F0F0FF

[Menu/Separator]
Color=#F0F0F010
