[Metadata]
Name=明月／Luna
Version=1
Author=佛振 <chen.sst@gmail.com>
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#EEEEECFF
HighlightColor=#FFFF7FFF
HighlightBackgroundColor=#00000040
HighlightCandidateColor=#FFFF7FFF
CandidateLabelColor=#EEEEECFF
HighlightCandidateLabelColor=#FFFF7FFF
CandidateCommentColor=#A5A5A5FF
HighlightCandidateCommentColor=#9D9C44FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#000000DD
BorderColor=#000000DD
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#00000040

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#EEEEECFF
HighlightCandidateColor=#FFFF7FFF

[Menu/Background]
Color=#000000DD
BorderColor=#000000DD
BorderWidth=1

[Menu/Highlight]
Color=#00000040

[Menu/Separator]
Color=#000000DD
