[Metadata]
Name=Wii
Version=1
Author=Patricivs <ipatrickmac@me.com>
Description=eosphoros desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#595757FF
HighlightColor=#33CCFFFF
HighlightBackgroundColor=#33CCFFFF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#C8C9CAFF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#C8C9CAFF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#EFEFEFFF
BorderColor=#EFEFEFFF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#33CCFFFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#595757FF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#EFEFEFFF
BorderColor=#EFEFEFFF
BorderWidth=1

[Menu/Highlight]
Color=#33CCFFFF

[Menu/Separator]
Color=#EFEFEFFF
