[Metadata]
Name=Gruvbox Light
Version=1
Author=Q
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#458588FF
HighlightColor=#CC241DFF
HighlightBackgroundColor=#EBDBB2FF
HighlightCandidateColor=#000000FF
CandidateLabelColor=#D65D0EFF
HighlightCandidateLabelColor=#98971AFF
CandidateCommentColor=#7F57A2FF
HighlightCandidateCommentColor=#000000FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FBF1C7FF
BorderColor=#EBDBB2FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#EBDBB2FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#458588FF
HighlightCandidateColor=#000000FF

[Menu/Background]
Color=#FBF1C7FF
BorderColor=#EBDBB2FF
BorderWidth=1

[Menu/Highlight]
Color=#EBDBB2FF

[Menu/Separator]
Color=#EBDBB2FF
