[Metadata]
Name=win10_weasel
Version=1
Author=luminosa
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#000000FF
HighlightColor=#000000FF
HighlightBackgroundColor=#A6D8FFFF
HighlightCandidateColor=#000000FF
CandidateLabelColor=#6F6F6FFF
HighlightCandidateLabelColor=#6F6F6FFF
CandidateCommentColor=#000000FF
HighlightCandidateCommentColor=#000000FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#F3F3F3FF
BorderColor=#DCDCDBFF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#A6D8FFFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#000000FF
HighlightCandidateColor=#000000FF

[Menu/Background]
Color=#F3F3F3FF
BorderColor=#DCDCDBFF
BorderWidth=1

[Menu/Highlight]
Color=#A6D8FFFF

[Menu/Separator]
Color=#DCDCDBFF
