[Metadata]
Name=幽能／Psionics
Version=1
Author=雨過之後、佛振
Description=xmjd6 desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#EEEEEEFF
HighlightColor=#EEEEEEFF
HighlightBackgroundColor=#00BCD4FF
HighlightCandidateColor=#FAFAFAFF
CandidateLabelColor=#EEEEEEFF
HighlightCandidateLabelColor=#FAFAFAFF
CandidateCommentColor=#808080FF
HighlightCandidateCommentColor=#444444FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#444444FF
BorderColor=#444444FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#00BCD4FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#EEEEEEFF
HighlightCandidateColor=#FAFAFAFF

[Menu/Background]
Color=#444444FF
BorderColor=#444444FF
BorderWidth=1

[Menu/Highlight]
Color=#00BCD4FF

[Menu/Separator]
Color=#444444FF
