[Metadata]
Name=Cat暗黑/CatDark
Version=1
Author=ProudCat
Description=xmjd6 desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#FFFFFF99
HighlightColor=#FFFFFFE5
HighlightBackgroundColor=#0A3AFAFF
HighlightCandidateColor=#FFFFFFE5
CandidateLabelColor=#FFFFFF85
HighlightCandidateLabelColor=#FFFFFFE5
CandidateCommentColor=#FFFFFF55
HighlightCandidateCommentColor=#C5C5C5FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#242424FF
BorderColor=#E0E0E0FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#0A3AFAFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#FFFFFF99
HighlightCandidateColor=#FFFFFFE5

[Menu/Background]
Color=#242424FF
BorderColor=#E0E0E0FF
BorderWidth=1

[Menu/Highlight]
Color=#0A3AFAFF

[Menu/Separator]
Color=#E0E0E0FF
