[Metadata]
Name=暗堂／Dark Temple
Version=1
Author=佛振 <chen.sst@gmail.com>, based on ir_black
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#E6E3D8FF
HighlightColor=#9ACFFFFF
HighlightBackgroundColor=#00000010
HighlightCandidateColor=#DAF692FF
CandidateLabelColor=#E6E3D8FF
HighlightCandidateLabelColor=#DAF692FF
CandidateCommentColor=#FF6C60FF
HighlightCandidateCommentColor=#DAF692FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#222222FF
BorderColor=#222222FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#00000010

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#E6E3D8FF
HighlightCandidateColor=#DAF692FF

[Menu/Background]
Color=#222222FF
BorderColor=#222222FF
BorderWidth=1

[Menu/Highlight]
Color=#00000010

[Menu/Separator]
Color=#222222FF
