[Metadata]
Name=銅鑼衛門／Doraemon
Version=1
Author=Patricivs <ipatrickmac@me.com>
Description=eosphoros desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#009FE8FF
HighlightColor=#FFFFFFFF
HighlightBackgroundColor=#009FE8FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#009FE8FF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#009FE8FF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FFFFFFFF
BorderColor=#009FE8FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#009FE8FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#009FE8FF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#FFFFFFFF
BorderColor=#009FE8FF
BorderWidth=1

[Menu/Highlight]
Color=#009FE8FF

[Menu/Separator]
Color=#009FE8FF
