[Metadata]
Name=Windows 10 Dark Blue
Version=1
Author=fbewivpjsbsby
Description=xmjd6 desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#F2F2F2FF
HighlightColor=#FFFFFFFF
HighlightBackgroundColor=#2072A3FF
HighlightCandidateColor=#F2F2F2FF
CandidateLabelColor=#888888FF
HighlightCandidateLabelColor=#F2F2F2FF
CandidateCommentColor=#888888FF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#1F1F1FFF
BorderColor=#2072A3FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#2072A3FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#F2F2F2FF
HighlightCandidateColor=#F2F2F2FF

[Menu/Background]
Color=#1F1F1FFF
BorderColor=#2072A3FF
BorderWidth=1

[Menu/Highlight]
Color=#2072A3FF

[Menu/Separator]
Color=#2072A3FF
