[Metadata]
Name=星際我爭霸／StarCraft
Version=1
Author=Contralisk <contralisk@gmail.com>, original artwork by Blizzard Entertainment
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#55BB30FF
HighlightColor=#96CBFEFF
HighlightBackgroundColor=#000000FF
HighlightCandidateColor=#AFFF70FF
CandidateLabelColor=#55BB30FF
HighlightCandidateLabelColor=#AFFF70FF
CandidateCommentColor=#D01010FF
HighlightCandidateCommentColor=#F01010FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#000000EE
BorderColor=#A01010FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#000000FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#55BB30FF
HighlightCandidateColor=#AFFF70FF

[Menu/Background]
Color=#000000EE
BorderColor=#A01010FF
BorderWidth=1

[Menu/Highlight]
Color=#000000FF

[Menu/Separator]
Color=#A01010FF
