[Metadata]
Name=藍精靈／Smurfs
Version=1
Author=skoj <skoj@qq.com>
Description=eosphoros desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#F6F6F6FF
HighlightColor=#6DBCDBFF
HighlightBackgroundColor=#6DBCDBFF
HighlightCandidateColor=#F6F6F6FF
CandidateLabelColor=#1778BFFF
HighlightCandidateLabelColor=#F6F6F6FF
CandidateCommentColor=#F6F6F6FF
HighlightCandidateCommentColor=#F6F6F6FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#1778BFFF
BorderColor=#E0EDF5FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#6DBCDBFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#F6F6F6FF
HighlightCandidateColor=#F6F6F6FF

[Menu/Background]
Color=#1778BFFF
BorderColor=#E0EDF5FF
BorderWidth=1

[Menu/Highlight]
Color=#6DBCDBFF

[Menu/Separator]
Color=#E0EDF5FF
