[Metadata]
Name=丁丁／Tintin
Version=1
Author=Patricivs <ipatrickmac@me.com>
Description=eosphoros desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#FFFFFFFF
HighlightColor=#91D8F7FF
HighlightBackgroundColor=#F16421FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#FFFFFFFF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#FFFFFFFF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#0095D9FF
BorderColor=#0095D9FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#F16421FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#FFFFFFFF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#0095D9FF
BorderColor=#0095D9FF
BorderWidth=1

[Menu/Highlight]
Color=#F16421FF

[Menu/Separator]
Color=#0095D9FF
