[Metadata]
Name=Cat光明/CatLight
Version=1
Author=ProudCat
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#4B4B4BFF
HighlightColor=#000000FF
HighlightBackgroundColor=#1F57FFFF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#4B4B4BFF
HighlightCandidateLabelColor=#C5C5C5FF
CandidateCommentColor=#4B4B4BFF
HighlightCandidateCommentColor=#C5C5C5FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#F3F3F3FF
BorderColor=#E0E0E0FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#1F57FFFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#4B4B4BFF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#F3F3F3FF
BorderColor=#E0E0E0FF
BorderWidth=1

[Menu/Highlight]
Color=#1F57FFFF

[Menu/Separator]
Color=#E0E0E0FF
