[Metadata]
Name=玫红 / MacRoseo
Version=1
Author=KyleBing
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#000000FF
HighlightColor=#000000FF
HighlightBackgroundColor=#FA114FFF
HighlightCandidateColor=#FA114FFF
CandidateLabelColor=#999999FF
HighlightCandidateLabelColor=#FA114F88
CandidateCommentColor=#27CCBBFF
HighlightCandidateCommentColor=#FA114FFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FFFFFFFF
BorderColor=#00000033
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#FA114FFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#000000FF
HighlightCandidateColor=#FA114FFF

[Menu/Background]
Color=#FFFFFFFF
BorderColor=#00000033
BorderWidth=1

[Menu/Highlight]
Color=#FA114FFF

[Menu/Separator]
Color=#00000033
