[Metadata]
Name=笆悉／Brasil
Version=1
Author=Patricivs <ipatrickmac@me.com>
Description=xmjd6 desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#FFFFFFFF
HighlightColor=#FFFFFFFF
HighlightBackgroundColor=#F7C716FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#FFFFFFFF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#FFFFFFFF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#119355FF
BorderColor=#119355FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#F7C716FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#FFFFFFFF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#119355FF
BorderColor=#119355FF
BorderWidth=1

[Menu/Highlight]
Color=#F7C716FF

[Menu/Separator]
Color=#119355FF
