[Metadata]
Name=MacRoseo
Version=1
Author=KyleBing
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#000000FF
HighlightColor=#000000FF
HighlightBackgroundColor=#FA114FFF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#000000FF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#27CCBBFF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FFFFFFFF
BorderColor=#D6D6D6FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#FA114FFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#000000FF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#FFFFFFFF
BorderColor=#D6D6D6FF
BorderWidth=1

[Menu/Highlight]
Color=#FA114FFF

[Menu/Separator]
Color=#D6D6D6FF
