[Metadata]
Name=祈澍
Version=1
Author=qishu
Description=xmjd6 desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#86F6CEFF
HighlightColor=#A6CA82FF
HighlightBackgroundColor=#3D4753FF
HighlightCandidateColor=#FB96AEFF
CandidateLabelColor=#86F6CEFF
HighlightCandidateLabelColor=#FB96AEFF
CandidateCommentColor=#86F6CEFF
HighlightCandidateCommentColor=#A6CA82FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#3D4753FF
BorderColor=#3D4753FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#3D4753FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#86F6CEFF
HighlightCandidateColor=#FB96AEFF

[Menu/Background]
Color=#3D4753FF
BorderColor=#3D4753FF
BorderWidth=1

[Menu/Highlight]
Color=#3D4753FF

[Menu/Separator]
Color=#3D4753FF
