[Metadata]
Name=北境暗色／Nord Dark
Version=1
Author=eosphoros desktop theme collection
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#87D8F5FF
HighlightColor=#F5C86EFF
HighlightBackgroundColor=#434C5DFF
HighlightCandidateColor=#77E0C0FF
CandidateLabelColor=#87D8F5FF
HighlightCandidateLabelColor=#77E0C0FF
CandidateCommentColor=#87B6E6FF
HighlightCandidateCommentColor=#77E0C0FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#333A47FF
BorderColor=#333A47FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#434C5DFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#87D8F5FF
HighlightCandidateColor=#77E0C0FF

[Menu/Background]
Color=#333A47FF
BorderColor=#333A47FF
BorderWidth=1

[Menu/Highlight]
Color=#434C5DFF

[Menu/Separator]
Color=#333A47FF
