[Metadata]
Name=致青春·Q改／So Young Q
Version=1
Author=Q
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#556B73FF
HighlightColor=#EEE8D5FF
HighlightBackgroundColor=#556B73FF
HighlightCandidateColor=#EEE8D5FF
CandidateLabelColor=#839191FF
HighlightCandidateLabelColor=#EEE8D5FF
CandidateCommentColor=#B97793FF
HighlightCandidateCommentColor=#EEE8D5FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FDF6E3FF
BorderColor=#CCC8C5FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#556B73FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#556B73FF
HighlightCandidateColor=#EEE8D5FF

[Menu/Background]
Color=#FDF6E3FF
BorderColor=#CCC8C5FF
BorderWidth=1

[Menu/Highlight]
Color=#556B73FF

[Menu/Separator]
Color=#CCC8C5FF
