# 晨星键道原创桌面皮肤：黑白极简。UTF-8，无外部图片与字体。

[about]
name=晨星·极简

[main]
scale=0
line_width=1
size=168,30
move=0,0,168,30
bg=#FAFAFA
border=#171717
radius=7
tran=0
name=12,3,144,24
name_font=Sans-serif 12
name_color=#171717

[main-dark]
bg=#171717
border=#EDEDED
name_color=#F7F7F7

[input]
scale=0
line_width=1
bg=#FAFAFA,#171717
border=#171717
size=260,42
msize=128,42
radius=7
code=10,5
cand=10,23
pad=3,6
space=12
offset=2,12
font=Sans-serif 13
color=#171717,#FFFFFF,#666666,#171717,#666666,#171717,#666666
line=1
caret=1
page=1 ◀▶ 0.6 #666666
no=0

[input-dark]
bg=#171717,#F2F2F2
border=#EDEDED
color=#F7F7F7,#111111,#AFAFAF,#F7F7F7,#AFAFAF,#F7F7F7,#AFAFAF
page=1 ◀▶ 0.6 #AFAFAF
