[Metadata]
Name=纯洁
Version=1
Author=xmjd6 desktop theme collection
Description=xmjd6 desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#EEEEEEFF
HighlightColor=#EEEEEEFF
HighlightBackgroundColor=#FAFAFAFF
HighlightCandidateColor=#000000FF
CandidateLabelColor=#EEEEEEFF
HighlightCandidateLabelColor=#000000FF
CandidateCommentColor=#808080FF
HighlightCandidateCommentColor=#000000FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#444444FF
BorderColor=#444444FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#FAFAFAFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#EEEEEEFF
HighlightCandidateColor=#000000FF

[Menu/Background]
Color=#444444FF
BorderColor=#444444FF
BorderWidth=1

[Menu/Highlight]
Color=#FAFAFAFF

[Menu/Separator]
Color=#444444FF
