[Metadata]
Name=曬經石／Solarized Rock
Version=1
Author=Aben <tntaben@gmail.com>, based on Ethan Schoonover's Solarized color scheme
Description=xmjd6 desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#839496FF
HighlightColor=#2AA198FF
HighlightBackgroundColor=#D33682FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#839496FF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#2AA198C0
HighlightCandidateCommentColor=#002B36FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#002B36FF
BorderColor=#002B36FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#D33682FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#839496FF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#002B36FF
BorderColor=#002B36FF
BorderWidth=1

[Menu/Highlight]
Color=#D33682FF

[Menu/Separator]
Color=#002B36FF
