[Metadata]
Name=輕盈／Brisk
Version=1
Author=skoj <skoj@qq.com>
Description=eosphoros desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#575757FF
HighlightColor=#DC3822FF
HighlightBackgroundColor=#FFFFFFFF
HighlightCandidateColor=#DC3822FF
CandidateLabelColor=#575757FF
HighlightCandidateLabelColor=#DC3822FF
CandidateCommentColor=#575757FF
HighlightCandidateCommentColor=#DC3822FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FFFFFFFF
BorderColor=#333333FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#FFFFFFFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#575757FF
HighlightCandidateColor=#DC3822FF

[Menu/Background]
Color=#FFFFFFFF
BorderColor=#333333FF
BorderWidth=1

[Menu/Highlight]
Color=#FFFFFFFF

[Menu/Separator]
Color=#333333FF
