[Metadata]
Name=Windows10 文文／Ayaya
Version=1
Author=Lufs X <i@isteed.cc>
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#121212FF
HighlightColor=#EB0081FF
HighlightBackgroundColor=#FCE4ECFF
HighlightCandidateColor=#EC407AFF
CandidateLabelColor=#858788FF
HighlightCandidateLabelColor=#F48FB1FF
CandidateCommentColor=#8E8E8EFF
HighlightCandidateCommentColor=#EC407AFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FFFFFFFF
BorderColor=#FFFFFFFF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#FCE4ECFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#121212FF
HighlightCandidateColor=#EC407AFF

[Menu/Background]
Color=#FFFFFFFF
BorderColor=#FFFFFFFF
BorderWidth=1

[Menu/Highlight]
Color=#FCE4ECFF

[Menu/Separator]
Color=#FFFFFFFF
