[Metadata]
Name=Windows 10 Blue
Version=1
Author=fbewivpjsbsby
Description=xmjd6 desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#000000FF
HighlightColor=#000000FF
HighlightBackgroundColor=#298FCCFF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#888888FF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#888888FF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FFFFFFFF
BorderColor=#298FCCFF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#298FCCFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#000000FF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#FFFFFFFF
BorderColor=#298FCCFF
BorderWidth=1

[Menu/Highlight]
Color=#298FCCFF

[Menu/Separator]
Color=#298FCCFF
