[Metadata]
Name=沙漠夜／Mojave Dark
Version=1
Author=xiehuc <xiehuc@gmail.com>
Description=eosphoros desktop palette replica (squirrel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#DDDDDEFF
HighlightColor=#DDDDDEFF
HighlightBackgroundColor=#005DCBFF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#858788FF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#DDDDDEFF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#202325FF
BorderColor=#020202FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#005DCBFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#DDDDDEFF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#202325FF
BorderColor=#020202FF
BorderWidth=1

[Menu/Highlight]
Color=#005DCBFF

[Menu/Separator]
Color=#020202FF
