[Metadata]
Name=高仿暗色 macOS
Version=1
Author=Lufs X <i@isteed.cc>
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#E8E8E8FF
HighlightColor=#000000D8
HighlightBackgroundColor=#0362DAFF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#7C7C7CFF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#0000003F
HighlightCandidateCommentColor=#808080FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#241F1EFF
BorderColor=#241F1EFF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#0362DAFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#E8E8E8FF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#241F1EFF
BorderColor=#241F1EFF
BorderWidth=1

[Menu/Highlight]
Color=#0362DAFF

[Menu/Separator]
Color=#241F1EFF
