[Metadata]
Name=孤寺／Lost Temple
Version=1
Author=佛振 <chen.sst@gmail.com>, based on ir_black
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#F6F3E8FF
HighlightColor=#CAE682FF
HighlightBackgroundColor=#CAE682FF
HighlightCandidateColor=#000000FF
CandidateLabelColor=#F6F3E8FF
HighlightCandidateLabelColor=#000000FF
CandidateCommentColor=#CAE682BB
HighlightCandidateCommentColor=#343D20BB
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#303030EE
BorderColor=#303030EE
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#CAE682FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#F6F3E8FF
HighlightCandidateColor=#000000FF

[Menu/Background]
Color=#303030EE
BorderColor=#303030EE
BorderWidth=1

[Menu/Highlight]
Color=#CAE682FF

[Menu/Separator]
Color=#303030EE
