[Metadata]
Name=谷歌／Google
Version=1
Author=skoj <skoj@qq.com>
Description=xmjd6 desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#000000FF
HighlightColor=#000000FF
HighlightBackgroundColor=#3975CEFF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#000000FF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#6D6D6DFF
HighlightCandidateCommentColor=#B0C6EBFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FFFFFFFF
BorderColor=#E2E2E2FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#3975CEFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#000000FF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#FFFFFFFF
BorderColor=#E2E2E2FF
BorderWidth=1

[Menu/Highlight]
Color=#3975CEFF

[Menu/Separator]
Color=#E2E2E2FF
