[Metadata]
Name=現代戰爭／Modern Warfare
Version=1
Author=P1461
Description=xmjd6 desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#DCFEABFF
HighlightColor=#FCFDFBFF
HighlightBackgroundColor=#636F67FF
HighlightCandidateColor=#DCFEABFF
CandidateLabelColor=#DCFEABFF
HighlightCandidateLabelColor=#DCFEABFF
CandidateCommentColor=#FBFDFCFF
HighlightCandidateCommentColor=#DCFEABFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#0D1B0AFF
BorderColor=#83AD4BFF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#636F67FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#DCFEABFF
HighlightCandidateColor=#DCFEABFF

[Menu/Background]
Color=#0D1B0AFF
BorderColor=#83AD4BFF
BorderWidth=1

[Menu/Highlight]
Color=#636F67FF

[Menu/Separator]
Color=#83AD4BFF
