[Metadata]
Name=晨星·极简／Eosphoros Mono
Version=1
Author=eosphoros-keytao
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#000000FF
HighlightColor=#000000FF
HighlightBackgroundColor=#000000FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#666666FF
HighlightCandidateLabelColor=#CCCCCCFF
CandidateCommentColor=#666666FF
HighlightCandidateCommentColor=#CCCCCCFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FFFFFFFF
BorderColor=#000000FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#000000FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#000000FF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#FFFFFFFF
BorderColor=#000000FF
BorderWidth=1

[Menu/Highlight]
Color=#000000FF

[Menu/Separator]
Color=#000000FF
