[Metadata]
Name=爱范儿黑
Version=1
Author=Astrian Zheng
Description=xmjd6 desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#C82428FF
HighlightColor=#FFFFFFFF
HighlightBackgroundColor=#000000FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#C82428FF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#FFFFFFFF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#000000FF
BorderColor=#000000FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#000000FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#C82428FF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#000000FF
BorderColor=#000000FF
BorderWidth=1

[Menu/Highlight]
Color=#000000FF

[Menu/Separator]
Color=#000000FF
