[Metadata]
Name=win11_weasel
Version=1
Author=luminosa
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#000000FF
HighlightColor=#000000FF
HighlightBackgroundColor=#B3FFFFFF
HighlightCandidateColor=#000000FF
CandidateLabelColor=#7C7C7CFF
HighlightCandidateLabelColor=#7C7C7CFF
CandidateCommentColor=#000000FF
HighlightCandidateCommentColor=#000000FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#F9F9F9FF
BorderColor=#E6E6E6FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#B3FFFFFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#000000FF
HighlightCandidateColor=#000000FF

[Menu/Background]
Color=#F9F9F9FF
BorderColor=#E6E6E6FF
BorderWidth=1

[Menu/Highlight]
Color=#B3FFFFFF

[Menu/Separator]
Color=#E6E6E6FF
