[Metadata]
Name=Windows 11 原生／Weasel
Version=1
Author=luminosa
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#000000FF
HighlightColor=#000000FF
HighlightBackgroundColor=#F0F0F0FF
HighlightCandidateColor=#000000FF
CandidateLabelColor=#7C7C7CFF
HighlightCandidateLabelColor=#424242FF
CandidateCommentColor=#616161FF
HighlightCandidateCommentColor=#424242FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#F9F9F9FF
BorderColor=#E5E5E5FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#F0F0F0FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#000000FF
HighlightCandidateColor=#000000FF

[Menu/Background]
Color=#F9F9F9FF
BorderColor=#E5E5E5FF
BorderWidth=1

[Menu/Highlight]
Color=#F0F0F0FF

[Menu/Separator]
Color=#E5E5E5FF
