[Metadata]
Name=碧水／Aqua
Version=1
Author=佛振 <chen.sst@gmail.com>
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#000000FF
HighlightColor=#000000FF
HighlightBackgroundColor=#0A3AFAEE
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#000000FF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#5A5A5AFF
HighlightCandidateCommentColor=#9DACFCFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#EEEEECEE
BorderColor=#EEEEECEE
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#0A3AFAEE

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#000000FF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#EEEEECEE
BorderColor=#EEEEECEE
BorderWidth=1

[Menu/Highlight]
Color=#0A3AFAEE

[Menu/Separator]
Color=#EEEEECEE
