[Metadata]
Name=純粹的本質／Purity of Essence
Version=1
Author=佛振
Description=eosphoros desktop palette replica (squirrel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#000000FF
HighlightColor=#000000FF
HighlightBackgroundColor=#444444FF
HighlightCandidateColor=#EEEEEEFF
CandidateLabelColor=#000000FF
HighlightCandidateLabelColor=#EEEEEEFF
CandidateCommentColor=#808080FF
HighlightCandidateCommentColor=#EEEEEEFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FAFAFAFF
BorderColor=#FAFAFAFF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#444444FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#000000FF
HighlightCandidateColor=#EEEEEEFF

[Menu/Background]
Color=#FAFAFAFF
BorderColor=#FAFAFAFF
BorderWidth=1

[Menu/Highlight]
Color=#444444FF

[Menu/Separator]
Color=#FAFAFAFF
