[Metadata]
Name=Mac绿
Version=1
Author=eosphoros desktop theme collection
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#3C3C3CFF
HighlightColor=#999999FF
HighlightBackgroundColor=#4CA132FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#999999FF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#999999FF
HighlightCandidateCommentColor=#999999FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FFFFFFFF
BorderColor=#FFFFFFFF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#4CA132FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#3C3C3CFF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#FFFFFFFF
BorderColor=#FFFFFFFF
BorderWidth=1

[Menu/Highlight]
Color=#4CA132FF

[Menu/Separator]
Color=#FFFFFFFF
