[Metadata]
Name=致青春／So Young
Version=1
Author=五磅兔 <zcunlin@foxmail.com>
Description=xmjd6 desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#657B83FF
HighlightColor=#839496FF
HighlightBackgroundColor=#2AA198FF
HighlightCandidateColor=#EEE8D5FF
CandidateLabelColor=#93A1A1FF
HighlightCandidateLabelColor=#EEE8D5FF
CandidateCommentColor=#268BD2FF
HighlightCandidateCommentColor=#EEE8D5FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FDF6E3FF
BorderColor=#EEE8D5FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#2AA198FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#657B83FF
HighlightCandidateColor=#EEE8D5FF

[Menu/Background]
Color=#FDF6E3FF
BorderColor=#EEE8D5FF
BorderWidth=1

[Menu/Highlight]
Color=#2AA198FF

[Menu/Separator]
Color=#EEE8D5FF
