[Metadata]
Name=星夜
Version=1
Author=lxetm
Description=xmjd6 desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#E2C564FF
HighlightColor=#E2C564FF
HighlightBackgroundColor=#242C3BFF
HighlightCandidateColor=#E2C564FF
CandidateLabelColor=#E2C564FF
HighlightCandidateLabelColor=#E2C564FF
CandidateCommentColor=#8C8454FF
HighlightCandidateCommentColor=#E2C564FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#242C3BFF
BorderColor=#396591FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#242C3BFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#E2C564FF
HighlightCandidateColor=#E2C564FF

[Menu/Background]
Color=#242C3BFF
BorderColor=#396591FF
BorderWidth=1

[Menu/Highlight]
Color=#242C3BFF

[Menu/Separator]
Color=#396591FF
