[Metadata]
Name=熊出沒／Kuma Shuzboz
Version=1
Author=Patricivs <ipatrickmac@me.com>
Description=xmjd6 desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#FFFFFFFF
HighlightColor=#F8B62DFF
HighlightBackgroundColor=#000000FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#FFFFFFFF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#FFFFFFFF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#F8B62DFF
BorderColor=#F8B62DFF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#000000FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#FFFFFFFF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#F8B62DFF
BorderColor=#F8B62DFF
BorderWidth=1

[Menu/Highlight]
Color=#000000FF

[Menu/Separator]
Color=#F8B62DFF
