[Metadata]
Name=DOTA 2
Version=1
Author=Patricivs <ipatrickmac@me.com>
Description=eosphoros desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#8F755CFF
HighlightColor=#DD4118FF
HighlightBackgroundColor=#DD4118FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#8F755CFF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#8F755CFF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#100F12FF
BorderColor=#100F12FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#DD4118FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#8F755CFF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#100F12FF
BorderColor=#100F12FF
BorderWidth=1

[Menu/Highlight]
Color=#DD4118FF

[Menu/Separator]
Color=#100F12FF
