#!/usr/bin/env python3
"""Validate structural Unicode rules in generated Emoji Lua tables."""

from __future__ import annotations

import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EMOJI_ROOT = ROOT / "opencc" / "eosphoros"
ROW_RE = re.compile(
    r'^\s*\["(?P<key>(?:\\.|[^"\\])*)"\]\s*=\s*"(?P<value>(?:\\.|[^"\\])*)",\s*$'
)
ZWJ = "\u200d"
VS = {"\ufe0e", "\ufe0f"}
KEYCAP = "\u20e3"
CANCEL_TAG = "\U000e007f"
REGIONAL_INDICATORS = range(0x1F1E6, 0x1F200)
TAG_CHARS = range(0xE0020, 0xE007F)


def unescape_lua_string(value: str) -> str:
    """Decode the small escape subset used by the generated Lua tables."""

    return re.sub(r"\\([\\\"nrt])", lambda match: {
        "\\": "\\",
        '"': '"',
        "n": "\n",
        "r": "\r",
        "t": "\t",
    }[match.group(1)], value)


def sequence_errors(text: str) -> list[str]:
    errors: list[str] = []
    for index, char in enumerate(text):
        codepoint = ord(char)
        previous = text[index - 1] if index else ""
        following = text[index + 1] if index + 1 < len(text) else ""
        if char == ZWJ and (
            not previous
            or not following
            or previous.isspace()
            or following.isspace()
            or previous == ZWJ
            or following == ZWJ
        ):
            errors.append("orphan or repeated ZWJ")
        if char in VS and (
            not previous or previous.isspace() or previous == ZWJ or previous in VS
        ):
            errors.append("orphan or repeated variation selector")
        if char == KEYCAP:
            base = text[index - 2] if previous in VS and index >= 2 else previous
            if base not in "#*0123456789":
                errors.append("keycap mark without #, *, or digit base")
        if codepoint in TAG_CHARS:
            start = index
            while start and ord(text[start - 1]) in TAG_CHARS:
                start -= 1
            if start == index and previous != "\U0001f3f4":
                errors.append("emoji tag sequence without black-flag base")
        if char == CANCEL_TAG and (
            not previous or ord(previous) not in TAG_CHARS
        ):
            errors.append("cancel tag outside an emoji tag sequence")
        if codepoint & 0xFFFF in {0xFFFE, 0xFFFF} or 0xFDD0 <= codepoint <= 0xFDEF:
            errors.append(f"Unicode noncharacter U+{codepoint:04X}")

    run = 0
    for char in text + " ":
        if ord(char) in REGIONAL_INDICATORS:
            run += 1
        else:
            if run % 2:
                errors.append("unpaired regional-indicator flag code point")
            run = 0

    return list(dict.fromkeys(errors))


def validate_file(path: Path) -> list[str]:
    errors: list[str] = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        match = ROW_RE.match(line)
        if not match:
            continue
        value = unescape_lua_string(match.group("value"))
        for message in sequence_errors(value):
            errors.append(f"{path.relative_to(ROOT).as_posix()}:{line_number}: {message}")
    return errors


def validate_repository(root: Path = EMOJI_ROOT) -> list[str]:
    # Only the Rime-Ice overlay is regenerated by the scheduled dictionary
    # sync. Validate that automatic boundary without silently rewriting the
    # separately maintained legacy txjx Emoji tables.
    paths = sorted(root.glob("eosphoros_emoji_extra*.lua"))
    if not paths:
        return [f"{root}: no Emoji Lua tables found"]
    return [error for path in paths for error in validate_file(path)]


def main() -> int:
    errors = validate_repository()
    if errors:
        print(f"Emoji validation failed with {len(errors)} error(s):", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print("Emoji Unicode sequence validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
