[Metadata]
Name=微信键盘深色
Version=1
Author=eosphoros desktop theme collection
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#EAE9E9FF
HighlightColor=#FFFFFFFF
HighlightBackgroundColor=#00B175FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#999999FF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#999999FF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#25292EFF
BorderColor=#25292EFF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#00B175FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#EAE9E9FF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#25292EFF
BorderColor=#25292EFF
BorderWidth=1

[Menu/Highlight]
Color=#00B175FF

[Menu/Separator]
Color=#25292EFF
