[Metadata]
Name=冷漠／Apathy
Version=1
Author=LIANG Hai
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#424242FF
HighlightColor=#424242FF
HighlightBackgroundColor=#E4F0FFFF
HighlightCandidateColor=#006EEEFF
CandidateLabelColor=#424242FF
HighlightCandidateLabelColor=#006EEEFF
CandidateCommentColor=#999999FF
HighlightCandidateCommentColor=#006EEEFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FFFFFFFF
BorderColor=#FFFFFFFF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#E4F0FFFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#424242FF
HighlightCandidateColor=#006EEEFF

[Menu/Background]
Color=#FFFFFFFF
BorderColor=#FFFFFFFF
BorderWidth=1

[Menu/Highlight]
Color=#E4F0FFFF

[Menu/Separator]
Color=#FFFFFFFF
