[Metadata]
Name=青橙
Version=1
Author=lxetm
Description=xmjd6 desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#E17507FF
HighlightColor=#E17507FF
HighlightBackgroundColor=#2D2D2EFF
HighlightCandidateColor=#11DADAFF
CandidateLabelColor=#E17507FF
HighlightCandidateLabelColor=#11DADAFF
CandidateCommentColor=#E17507FF
HighlightCandidateCommentColor=#11DADAFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#2D2D2EFF
BorderColor=#849494FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#2D2D2EFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#E17507FF
HighlightCandidateColor=#11DADAFF

[Menu/Background]
Color=#2D2D2EFF
BorderColor=#849494FF
BorderWidth=1

[Menu/Highlight]
Color=#2D2D2EFF

[Menu/Separator]
Color=#849494FF
