[Metadata]
Name=北方浅色
Version=1
Author=eosphoros desktop theme collection
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#81A1C1FF
HighlightColor=#B48EADFF
HighlightBackgroundColor=#D8DEE9FF
HighlightCandidateColor=#5E81ACFF
CandidateLabelColor=#81A1C1FF
HighlightCandidateLabelColor=#5E81ACFF
CandidateCommentColor=#88C0D0FF
HighlightCandidateCommentColor=#5E81ACFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#ECEFF4FF
BorderColor=#ECEFF4FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#D8DEE9FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#81A1C1FF
HighlightCandidateColor=#5E81ACFF

[Menu/Background]
Color=#ECEFF4FF
BorderColor=#ECEFF4FF
BorderWidth=1

[Menu/Highlight]
Color=#D8DEE9FF

[Menu/Separator]
Color=#ECEFF4FF
