[Metadata]
Name=米兰
Version=1
Author=xmjd6 desktop theme collection
Description=xmjd6 desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#424242FF
HighlightColor=#424242FF
HighlightBackgroundColor=#3B80F5FF
HighlightCandidateColor=#FFFFFFFF
CandidateLabelColor=#424242FF
HighlightCandidateLabelColor=#FFFFFFFF
CandidateCommentColor=#999999FF
HighlightCandidateCommentColor=#FFFFFFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FFFFFFFF
BorderColor=#FFFFFFFF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#3B80F5FF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#424242FF
HighlightCandidateColor=#FFFFFFFF

[Menu/Background]
Color=#FFFFFFFF
BorderColor=#FFFFFFFF
BorderWidth=1

[Menu/Highlight]
Color=#3B80F5FF

[Menu/Separator]
Color=#FFFFFFFF
