[Metadata]
Name=浮尘／Dust
Version=1
Author=Superoutman <asticosmo@gmail.com>
Description=xmjd6 desktop palette replica (squirrel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#555555FF
HighlightColor=#9E9E9EFF
HighlightBackgroundColor=#E4F0FFFF
HighlightCandidateColor=#000000FF
CandidateLabelColor=#CBCBCBFF
HighlightCandidateLabelColor=#000000FF
CandidateCommentColor=#999999FF
HighlightCandidateCommentColor=#9E9E9EFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#FFFFFFEE
BorderColor=#93B6E0FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#E4F0FFFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#555555FF
HighlightCandidateColor=#000000FF

[Menu/Background]
Color=#FFFFFFEE
BorderColor=#93B6E0FF
BorderWidth=1

[Menu/Highlight]
Color=#E4F0FFFF

[Menu/Separator]
Color=#93B6E0FF
