[Metadata]
Name=澳門／Macau
Version=1
Author=Patricivs <ipatrickmac@me.com>
Description=xmjd6 desktop palette replica (weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#FFFFFFFF
HighlightColor=#FFFFFFFF
HighlightBackgroundColor=#FFFFFFFF
HighlightCandidateColor=#FFD900FF
CandidateLabelColor=#FFFFFFFF
HighlightCandidateLabelColor=#FFD900FF
CandidateCommentColor=#FFFFFFFF
HighlightCandidateCommentColor=#FFD900FF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#00A381FF
BorderColor=#00A381FF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#FFFFFFFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#FFFFFFFF
HighlightCandidateColor=#FFD900FF

[Menu/Background]
Color=#00A381FF
BorderColor=#00A381FF
BorderWidth=1

[Menu/Highlight]
Color=#FFFFFFFF

[Menu/Separator]
Color=#00A381FF
