[Metadata]
Name=蓝水鸭／Mint Light Blue
Version=1
Author=Mintimate <"Mintimate's Blog">
Description=eosphoros desktop palette replica (squirrel, weasel)
ScaleWithDPI=True

[InputPanel]
NormalColor=#424242FF
HighlightColor=#6495EDFF
HighlightBackgroundColor=#6495EDFF
HighlightCandidateColor=#EFEFEFFF
CandidateLabelColor=#C8C9CAFF
HighlightCandidateLabelColor=#EFEFEFFF
CandidateCommentColor=#C8C9CAFF
HighlightCandidateCommentColor=#EFEFEFFF
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#EFEFEFFF
BorderColor=#EFEFEFFF
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#6495EDFF

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#424242FF
HighlightCandidateColor=#EFEFEFFF

[Menu/Background]
Color=#EFEFEFFF
BorderColor=#EFEFEFFF
BorderWidth=1

[Menu/Highlight]
Color=#6495EDFF

[Menu/Separator]
Color=#EFEFEFFF
